alias: Motionevents -> event.txt
trigger:
  - platform: state
    entity_id: sensor.esp8266_01_pir
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: sensor.esp8266_02_pir
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: '0'
    to: '8'
  - platform: state
    entity_id: input_boolean.chrishome
    from: 'off'
    to: 'on'
action:
  - service: notify.event
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }}: Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde aktiviert!