homeassistant:
  name: !secret name

  latitude: !secret latitude

  longitude: !secret longitude

  elevation: 429

  unit_system: metric

  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml

  packages: !include_dir_named packages


frontend:
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    dark:
      primary-color: "#444649"
    orange:
      dark-primary-color: "#444649"
      primary-color: "#444649"
      light-primary-color: "#FFE0B2"
      primary-text-color: "#212121"
      paper-toggle-button-checked-ink-color: "#2d3a4f"
      paper-toggle-button-checked-button-color: "#2d3a4f"
      paper-toggle-button-checked-bar-color: "#726c64"
      paper-slider-knob-color: "#2d3a4f"
      paper-slider-knob-start-color: "#2d3a4f"
      paper-slider-pin-color: "#2d3a4f"
      paper-slider-active-color: "#2d3a4f"
      paper-slider-secondary-color: "#FFE0B2"
    dark_red:
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b"
      paper-card-header-color: "var(--paper-item-icon-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
http:
  api_password: !secret api_password
  ssl_certificate: /home/homeassistant/sslcert/fullchain.pem
  ssl_key: /home/homeassistant/sslcert/privkey.pem

config:
cloud:
  alexa:
    filter:
      include_entities:
        - light.flur
        - light.schlafzimmer
      include_domains:
        - switch
      exclude_entities:
        - switch.outside
    entity_config:
      light.flur:
        name: Flurlicht
        description: Flurlicht
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch:
        name: Steckdose
        description: mpd steckdose
      switch.receiver:
        name: Verstärker
        description: Verstärker
      switch.11011_a:
        display_categories: LIGHT

updater:

logger:
  default: error
  logs:
    homeassistant.components.camera.generic: fatal
    homeassistant.components.shell_command: fatal
    requests.exceptions.ConnectionError: fatal

#discovery:

conversation:

history:

recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret mysql_db_path_local
  include:
    domains:
      - binary_sensor
      - switch
      - light
      - media_player
      - device_tracker
    entities:
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.average_load_1m
      - sensor.average_load_5m
      - sensor.average_load_15m
      - sensor.cpu_temperature
      - sensor.cpu_used
      - sensor.disk_free_
      - sensor.disk_used_
      - sensor.disk_used__2
      - sensor.hauptrettungswache__zuhause
      - sensor.luftfeuchtigkeit_esp8266_01
      - sensor.luftfeuchtigkeit_esp8266_02
      - sensor.luftfeuchtigkeit_esp8266_03
      - sensor.qnap1_free_space_datavol1
      - sensor.qnap1_cpu_usage
      - sensor.qnap1_network_down_eth0
      - sensor.qnap1_network_up_eth0
      - sensor.sonoff1_gesamtverbrauch
      - sensor.sonoff1_kosten_gesamt
      - sensor.sonoff1_kosten_gestern
      - sensor.sonoff1_kosten_heute
      - sensor.sonoff2_gesamtverbrauch
      - sensor.sonoff2_kosten_gesamt
      - sensor.sonoff2_kosten_gestern
      - sensor.sonoff2_kosten_heute
      - sensor.sonoff3_gesamtverbrauch
      - sensor.sonoff3_kosten_gesamt
      - sensor.sonoff3_kosten_gestern
      - sensor.sonoff3_kosten_heute
      - sensor.sonoff4_gesamtverbrauch
      - sensor.sonoff4_kosten_gesamt
      - sensor.sonoff4_kosten_gestern
      - sensor.sonoff4_kosten_heute
      - sensor.sonoff5_gesamtverbrauch
      - sensor.sonoff5_kosten_gesamt
      - sensor.sonoff5_kosten_gestern
      - sensor.sonoff5_kosten_heute
      - sensor.sonoff1_momentane_leistung
      - sensor.sonoff2_momentane_leistung
      - sensor.sonoff3_momentane_leistung
      - sensor.sonoff4_momentane_leistung
      - sensor.sonoff5_momentane_leistung
      - sensor.tankstelle_super
      - sensor.temperatur_esp8266_01
      - sensor.temperatur_esp8266_02
      - sensor.temperatur_esp8266_03
      - sensor.zuhause__marienhospital
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.esp32_01_battery_value
 #pihole stats
      - switch.pihole
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.unique_domains
      - sensor.queries_forwarded
      - sensor.queries_cached
      - sensor.pihole_dns
      - sensor.pihole_blocking


    

influxdb:
  host: 127.0.0.1


logbook:

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

sun:

# # Emulated Hue -> Amazon Echo 
# emulated_hue:
  # off_maps_to_on_domains:
    # - scene
  # expose_by_default: true
  # exposed_domains:
    # - light
    # - switch
    # - scene

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

wemo:
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip


tradfri:
  host: !secret tradfri_ip


##################
#    INCLUDES    #
##################
automation: !include_dir_list automations/
#binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include_dir_merge_named groups/
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include includes/shell_command.yaml
switch: !include_dir_list switches/
tts: !include includes/tts.yaml




