homeassistant:
  name: !secret name

  latitude: !secret latitude

  longitude: !secret longitude

  elevation: 429

  unit_system: metric

  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml

  packages: !include_dir_named packages


frontend:
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    dark:
      primary-color: "#444649"
    orange:
      dark-primary-color: "#444649"
      primary-color: "#444649"
      light-primary-color: "#FFE0B2"
      primary-text-color: "#212121"
      paper-toggle-button-checked-ink-color: "#2d3a4f"
      paper-toggle-button-checked-button-color: "#2d3a4f"
      paper-toggle-button-checked-bar-color: "#726c64"
      paper-slider-knob-color: "#2d3a4f"
      paper-slider-knob-start-color: "#2d3a4f"
      paper-slider-pin-color: "#2d3a4f"
      paper-slider-active-color: "#2d3a4f"
      paper-slider-secondary-color: "#FFE0B2"
http:
   api_password: !secret api_password

config:

updater:

logger:
  default: error

#discovery:

conversation:

history:

recorder:
  purge_days: 30
  db_url: !secret mysql_db_path

logbook:

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

sun:

# Emulated Hue -> Amazon Echo 
emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

wemo:
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip


tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_api_key

##################
#    INCLUDES    #
##################
automation: !include_dir_list automations/
#binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include_dir_merge_named groups/
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_slider: !include includes/input_slider.yaml
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include includes/shell_command.yaml
switch: !include_dir_list switches/
tts: !include includes/tts.yaml




