homeassistant:
  name: !secret name

  latitude: !secret latitude

  longitude: !secret longitude

  elevation: 429

  unit_system: metric

  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml

frontend:

http:
   api_password: !secret api_password
config:

logger:
  default: warn

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
#  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

updater:

discovery:

conversation:

history:

recorder:
  purge_days: 365
  db_url: !secret mysql_db_path

logbook:

sun:

# Emulated Hue -> Amazon Echo 
emulated_hue:

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

##################
#    INCLUDES    #
##################
switch: !include_dir_list switches/
group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_list automations/
sensor: !include_dir_merge_list sensors/
notify: !include includes/notify.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

device_tracker:
#  - platform: ddwrt
#    host: !secret ddwrt_host
#    username: !secret ddwrt_user
#    password: !secret ddwrt_pw
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 20
    exclude:
    - 192.168.0.27
    - 192.168.0.26
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: bluetooth_tracker
  - platform: ping
    hosts:
       WKS_Alekto: 192.168.0.29
       ESP8266_01_Ping: 192.168.0.80
       ESP8266_02_Ping: 192.168.0.81
       ESP8266_03_Ping: 192.168.0.82
       ESP8266_04_Ping: 192.168.0.83
#      AmazonEchoDot: 192.168.0.97

#mjpeg stream rpi1 cam / generic ip cam
camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.0.23/html/cam_pic_new.php?
    name: RPi1 IR Cam
  - platform: generic
    name: Google Map Stuttgart
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center=48.77,9.15&zoom=10&size=500x500&maptype=roadmap
    limit_refetch_to_url_change: true

### Android IP Cam OPT
#android_ip_webcam:
#  - host: 192.168.0.102
#    name: LED Cam

#Kodi 1OG
media_player:
  - platform: kodi
    host: 192.168.0.21
    port: 80

wemo:
  static:
    - 192.168.0.31
    - 192.168.0.33

##################
#    INPUT       #
##################
input_boolean:
  chrishome:
    name: "Christoph"
    initial: on
    icon: mdi:cellphone-iphone

input_slider:
  tuerlicht_intervall:
    name: Türlicht Slider
    initial: 30
    min: 0
    max: 60
    step: 1
    unit_of_measurement: seconds
    icon: mdi:target

input_select:
  tuerlicht:
    name: Wie lange soll das Türlicht brennen?
    options:
     - 5
     - 15
     - 30
     - 45
     - 60
    initial: 30
    icon: mdi:panda

  led_mqtt:
    name: welche led darf es sein?
    options:
     - Rot
     - Gelb
     - Grün
     - Alle
    initial: Alle
    icon: mdi:panda

