homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 429
  unit_system: metric
  time_zone: Europe/Berlin
  #customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs :
    - /home/homeassistant/raspicam
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    #https://github.com/Gluwc/bar-card
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    #https://github.com/kalkih/mini-media-player
    - url: /hacsfiles/mini-media-player/mini-media-player.js
      type: module
     #https://github.com/thomasloven/lovelace-card-tools
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    #https://github.com/thomasloven/lovelace-layout-card
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: js
    #https://github.com/custom-cards/vertical-stack-in-card
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    #https://github.com/thomasloven/lovelace-auto-entities/blob/master/auto-entities.js
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: js
    #https://github.com/thomasloven/lovelace-fold-entity-row/blob/master/fold-entity-row.js
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: js
  #https://github.com/thomasloven/lovelace-toggle-lock-entity-row
    - url: /hacsfiles/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
      type: js
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: js
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/search-card/search-card.js
      type: module
    - url: /hacsfiles/love-lock-card/love-lock-card.js
      type: module
    - url: /hacsfiles/power-usage-card-regex/power-usage-card-regex.js
      type: module


http:
  ssl_certificate: /home/homeassistant/sslcert/fullchain.pem
  ssl_key: /home/homeassistant/sslcert/privkey.pem

config:

system_health:

updater:

hacs:
  token: !secret github_token_hacs


breaking_changes:

#discovery:
mobile_app:
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.de

conversation:

history:

map:

influxdb:
  host: 127.0.0.1

logbook:
person:

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

sun:

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

wemo:
  discovery: false
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip
nextcloud:
  url: !secret nextcloud_url
  username: !secret nextcloud_user
  password: !secret nextcloud_passwd
#tradfri:
#  host: !secret tradfri_ip

##################
#    INCLUDES    #
##################
automation: !include_dir_list automations/
#binary_sensor: !include includes/binary_sensor.yaml
#camera: !include includes/camera.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
#group: !include_dir_merge_named groups/
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
logger: !include includes/logger.yaml
#media_player: !include includes/media_player.yaml
recorder: !include includes/recorder.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
tts: !include includes/tts.yaml
zone: !include includes/zone.yaml
