homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 429
  unit_system: metric
  time_zone: Europe/Berlin
  #customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs :
    - /home/homeassistant/raspicam
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    #https://github.com/Gluwc/bar-card
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    #https://github.com/kalkih/mini-media-player
    - url: /hacsfiles/mini-media-player/mini-media-player.js
      type: module
     #https://github.com/thomasloven/lovelace-card-tools
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    #https://github.com/thomasloven/lovelace-layout-card
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: js
    #https://github.com/custom-cards/vertical-stack-in-card
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    #https://github.com/thomasloven/lovelace-fold-entity-row/blob/master/fold-entity-row.js
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/search-card/search-card.js
      type: module
    - url: /hacsfiles/love-lock-card/love-lock-card.js
      type: module
    - url: /hacsfiles/power-usage-card-regex/power-usage-card-regex.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/restriction-card/restriction-card.js
      type: module
    - url: /hacsfiles/slider-button-card/slider-button-card.js
      type: module
    - url: /hacsfiles/uptime-card/uptime-card.js
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/tankerkoenig-card/tankerkoenig-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module

http:
  ssl_certificate: /home/homeassistant/sslcert/fullchain.pem
  ssl_key: /home/homeassistant/sslcert/privkey.pem

config:

system_health:

updater:

hacs:
  token: !secret github_token_hacs




#discovery:
mobile_app:
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.de

conversation:

history:

map:

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.0.27
  port: 8086
  token: !secret influx2_token
  organization: !secret influx2_org
  bucket: home_assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entity_globs:
      - automation.*
      - camera.*
      - device_tracker.*
      - media_player.*
      - remote*
      - scene.*
      - script.*
      - zone.*
    domains:
      - persistent_notification
      - person

logbook:
person:

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

sun:

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret


nextcloud:
  url: !secret nextcloud_url
  username: !secret nextcloud_user
  password: !secret nextcloud_passwd
#tradfri:
#  host: !secret tradfri_ip

##################
#    INCLUDES    #
##################
automation: !include_dir_list automations/
#binary_sensor: !include includes/binary_sensor.yaml
#camera: !include includes/camera.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
#group: !include_dir_merge_named groups/
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
logger: !include includes/logger.yaml
#media_player: !include includes/media_player.yaml
recorder: !include includes/recorder.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
tts: !include includes/tts.yaml
zone: !include includes/zone.yaml
#wake_on_lan
wake_on_lan:
#Spotify
spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret
