homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 429
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /home/homeassistant/raspicam
frontend:

lovelace:
  mode: yaml

http:
  ssl_certificate: /home/homeassistant/sslcert/fullchain.pem
  ssl_key: /home/homeassistant/sslcert/privkey.pem

config:
system_health:
updater:
hacs:
  token: !secret github_token_hacs
  theme: true
  python_script: true
breaking_changes:
discovery:
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.de

conversation:

history:

map:

influxdb:
  host: 127.0.0.1

logbook:
person:
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

sun:

#Google Calender
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

wemo:
  discovery: false
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip

#tradfri:
#  host: !secret tradfri_ip

##################
#    INCLUDES    #
##################
automation: !include_dir_list automations/
#binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
#group: !include_dir_merge_named groups/
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media_player.yaml
recorder: !include includes/recorder.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include includes/shell_command.yaml
switch: !include_dir_list switches/
tts: !include includes/tts.yaml
zone: !include includes/zone.yaml
