resources:
  #https://github.com/Gluwc/bar-card
  - url: /local/bar-card.js
    type: js
  #https://github.com/kalkih/mini-media-player
  - url: /local/mini-media-player-bundle.js
    type: module
   #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js
    type: js
  #https://github.com/thomasloven/lovelace-layout-card
  - url: /local/layout-card.js
    type: js
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js
    type: js
  #https://github.com/custom-cards/tracker-card
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  #https://github.com/thomasloven/lovelace-auto-entities/blob/master/auto-entities.js
  - url: /local/auto-entities.js
    type: js
  #https://github.com/thomasloven/lovelace-fold-entity-row/blob/master/fold-entity-row.js
  - url: /local/fold-entity-row.js
    type: js
#https://github.com/thomasloven/lovelace-toggle-lock-entity-row
  - url: /local/toggle-lock-entity-row.js
    type: js

title: HomeAssistant
views:
  - !include lovelace/000_home_view.yaml
  - !include lovelace/010_service_view.yaml
  - !include lovelace/020_elw_view.yaml
  - !include lovelace/030_media_view.yaml
  - !include lovelace/040_first_floor_view.yaml
  - !include lovelace/050_weather_view.yaml
  - !include lovelace/060_waste_view.yaml
  - !include lovelace/065_network.yaml
  - !include lovelace/070_sensor_view.yaml
  - !include lovelace/080_sonoff_view.yaml
  - !include lovelace/090_zwave_view.yaml
  - !include lovelace/100_family_view.yaml

  - !include lovelace/970_test3_view.yaml
  - !include lovelace/980_test2_view.yaml
  - !include lovelace/999_test_view.yaml
