resources:
  #https://github.com/Gluwc/bar-card
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  #https://github.com/kalkih/mini-media-player
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
   #https://github.com/thomasloven/lovelace-card-tools
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  #https://github.com/thomasloven/lovelace-layout-card
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js

  #https://github.com/thomasloven/lovelace-auto-entities/blob/master/auto-entities.js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: js
  #https://github.com/thomasloven/lovelace-fold-entity-row/blob/master/fold-entity-row.js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
#https://github.com/thomasloven/lovelace-toggle-lock-entity-row
  - url: /community_plugin/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
    type: js
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
swipe_nav:
  animate: swipe
  swipe_amount: 15
title: HomeAssistant
views:
  - !include lovelace/000_home_view.yaml
  - !include lovelace/010_service_view.yaml
  - !include lovelace/020_elw_view.yaml
  - !include lovelace/021_pc_view.yaml
  - !include lovelace/025_elw_camera_view.yaml
  - !include lovelace/030_media_view.yaml
  - !include lovelace/040_first_floor_view.yaml
  - !include lovelace/050_weather_view.yaml
  - !include lovelace/060_waste_view.yaml
  - !include lovelace/065_network.yaml
  - !include lovelace/070_sensor_view.yaml
  - !include lovelace/080_sonoff_view.yaml
  - !include lovelace/090_zwave_view.yaml
  - !include lovelace/100_family_view.yaml

  - !include lovelace/970_test3_view.yaml
  - !include lovelace/980_test2_view.yaml
  - !include lovelace/999_test_view.yaml
