alias: "autossh Alarm"
initial_state: False
trigger:
  platform: state
  entity_id: sensor.process_autossh
  from: 'on'
  to: 'off'
action:
  - service: notify.pushbullet
    data:
      title: 'HomeAssistant: Process Monitor'
      message: '{{ states.sensor.date__time.state }}: Der SSH Tunnel läuft nicht!'
  - service: notify.email
    data:
      title: 'HomeAssistant: Process Monitor'
      message: '{{ states.sensor.date__time.state }}: Der SSH Tunnel läuft nicht!'