#Thanks 2 Bob_NL (https://community.home-assistant.io/t/intruder-alert/24084)
alias: "Send notification upon failed login attempt"
initial_state: True
trigger:
  - platform: state
    entity_id: persistent_notification.httplogin
condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != off }}"
action:
  - service: notify.pushbullet
    data_template:
      title: "Failed Home Assistant login attempt!"
      message: "{{ trigger.to_state.state }}"
      data:
        url: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ states.persistent_notification.httplogin.state.split ("from ") [1]}}