### Thanks 2 @brahmafear (initial version)
alias: Benachrichtigung aller Bewegunsgmelder in der ELW 
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    to: '8'
  - platform: state
    entity_id: sensor.esp8266_02_pir
    from: '0'
    to: '1'
  - platform: state
    entity_id: sensor.esp32_01_door_state
    from: 'closed'
    to: 'open'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'input_boolean.chrishome'
      state: 'off'
    - condition: template
      value_template: >
        {% if states.automation.benachrichtigung_aller_bewegunsgmelder_in_der_elw.last_triggered is not none %}
          {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.benachrichtigung_aller_bewegunsgmelder_in_der_elw.attributes.last_triggered) | int > 60 %} true {% else %} false
          {% endif %}
        {% else %}
        false
        {% endif %}
action:
  - service: notify.pushbullet
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde aktiviert!