### https://github.com/brahmafear/hass_config/blob/master/yaml/automation/motion_alarm.yaml
### Thanks 2 @brahmafear
alias: Benachrichtigung aller Bewegunsgmelder in der ELW 
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    to: '8'
  - platform: state
    entity_id: sensor.esp8266_02_pir
    from: '0'
    to: '1'
  - platform: state
    entity_id: sensor.esp32_01_door_state
    from: 'closed'
    to: 'open'
condition:
  condition: state
  entity_id: input_boolean.chrishome
  state: 'off'
action:
  - service: notify.pushbullet
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde aktiviert!