alias: 'MQTT Home State Pushbullet'

initial_state: False
trigger:
  platform: mqtt
  topic: 'state'


action:
  - service: notify.pushbullet
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }} MQTT Home State Switch via Tasker is  now {{ states.switch.christoph_mqtt.state }}. (HomeSwitch {{ states.input_boolean.chrishome.state }})