alias: ESP8266 Sensor State
trigger:
  - platform: state
    entity_id: device_tracker.esp8266_01_ping
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: device_tracker.esp8266_02_ping
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: device_tracker.esp8266_03_ping
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: device_tracker.esp8266_04_ping
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: device_tracker.esp8266_05_ping
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
action:
  - service: notify.pushbullet
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }} {{ trigger.to_state.attributes.friendly_name }} ist offline!