alias: ESP8266 Sensor State
trigger:
  - platform: state
    entity_id: device_tracker.esp8266_01
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: device_tracker.esp8266_02
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: device_tracker.esp8266_03
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: device_tracker.esp8266_04
    from: 'home'
    to: 'not_home'
action:
  - service: notify.pushbullet
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }} {{ trigger.to_state.attributes.friendly_name }} ist offline!