### Thanks to @dal3h and @CCOSTAN
alias: home_assistant_update_notification
trigger:
  - platform: state
    entity_id: updater.updater
condition:
  - condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"
action:
  - service: notify.pushbullet
    data_template:
      message: "Es gibt eine neue HA Version! Home Assistant {{ states('updater.updater') }}."
  - service: persistent_notification.create
    data:
      title: "Update Available"
      message: "Es gibt eine neue HA Version! {{ states('updater.updater') }}. - {{ as_timestamp(now()) | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}"
      notification_id: "update_available" 