alias: 'Notify Cloud ESP IP'
initial_state: False
trigger:
  platform: mqtt
  topic: 'sensor_esp8266_cloud/status_ip'
action:
  - service: notify.pushbullet
    data_template:
      message: >
        {{ now().strftime('%d.%m.%Y %H:%M:%S') }}: Die intere IPv4 des ESP Cloudboards ist: {{ states.sensor.esp8266_ip_cloud.state }}