alias: Benachrichtigung aller Bewegungsmelder ELW -> elwmotion.txt
initial_state: False
trigger:
  - platform: state
    entity_id: sensor.esp8266_02_pir
    from: '0'
    to: '1'
  - platform: state
    entity_id: sensor.esp8266_02_radar
    from: '0'
    to: '1'
  - platform: state
    entity_id: input_boolean.chrishome
    from: 'off'
    to: 'on'
action:
  - service: notify.motionelw
    data_template:
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }}: Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde geaendert!