alias: when gone enable motionlog
initial_state: 'off'
trigger:
  platform: state
  entity_id: input_boolean.chrishome
  from: 'on'
  to: 'off'
action:
  - service: shell_command.rmradarlog
  - service: automation.turn_on
    entity_id: automation.benachrichtigung_aller_bewegungsmelder_elw__elwmotiontxt
  - service: notify.pushbullet
    data_template:
      message: >
         {{ states.sensor.date__time.state }} motion logging  wurde angeschaltet!
