alias: 'ELW Licht ausschalten wenn BT nicht gefunden'
trigger:
    - platform: state
      entity_id: device_tracker.oneplus3bt
      to: 'not_home'
      for:
        minutes: 2
action:
    - service: homeassistant.turn_on
      entity_id: script.elw_lampen_aus
#    - service: notify.pushbullet
#      data:
#        message: 'Alle Lichter in der ELW wurden ausgeschaltet da dass BT Gerät nicht gefunden wurde!'