alias: Bewegungsmelder ELW Licht Z-Wave
initial_state: True
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_burglar
  from: '0'
  to: '8'
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: state
    entity_id: device_tracker.pixel_2_xl
    state: "home"
  - condition: state
    entity_id: light.flur
    state: "off"
action:
  - service: scene.turn_on
    entity_id: scene.flurrelax
  - delay: '{{ states.input_select.tuerlicht.state | int }}'
  - service: scene.turn_on
    entity_id: scene.fluraus