alias: "Bewegungsmelder ELW LED ESP 8266 PIR"
initial_state: False
trigger:
  platform: mqtt
  topic: sensor_esp8266_02/motion
  payload: 'on'
condition:
#  - condition: state
#    entity_id: sun.sun
#    state: "below_horizon"
  - condition: state
    entity_id: device_tracker.pixel_2_xl
    state: "home"
action:
  - service: switch.turn_on
    entity_id: switch.grune_led