alias: Auto AV Quelle PC
initial_state: True
trigger:
  platform: state
  entity_id: media_player.volumio
  from: 'playing'
  to: 'paused'
condition:
#  - condition: state
#    state: "home"
#    entity_id: device_tracker.pixel_2_xl
action:
  - service: media_player.select_source
    entity_id: media_player.yamaha_receiver
    data:
        source: PC