alias: "Bewegungsmelder ELW Licht ESP 8266 PIR"
initial_state: False
trigger:
  platform: mqtt
  topic: sensor_esp8266_01/motion
  payload: 'on'
condition:
#  - condition: state
#    entity_id: sun.sun
#    state: "below_horizon"
  - condition: state
    entity_id: device_tracker.oneplus3bt
    state: "home"
  - condition: state
    entity_id: switch.110112
    state: "off"
action:
  - service: switch.turn_on
    entity_id: switch.110112