##############################################################
### Packages / sonoff9                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff9:
      friendly_name: "Esszimmer"
      icon: mdi:lamp
    sensor.sonoff9_ipv4:
      friendly_name: IPv4 Sonoff 8
      icon: mdi:server-network
    sensor.sonoff9_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast



sensor:

### Reading the values from the tasmota mqtt string



  - platform: mqtt
    name: "sonoff9 uptime"
    state_topic: "tele/sonoff9/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff9/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"






### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff9"
    state_topic: "stat/sonoff9/POWER"
    command_topic: "cmnd/sonoff9/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
