##############################################################
### Packages / sonoff_09                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff_09:
      friendly_name: "Esszimmer Türe"
      icon: mdi:lamp
    sensor.sonoff_09_ipv4:
      friendly_name: IPv4 Sonoff 9
      icon: mdi:server-network
    sensor.sonoff_09_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast



sensor:

### Reading the values from the tasmota mqtt string



  - platform: mqtt
    name: "sonoff_09 uptime"
    state_topic: "tele/sonoff_09/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff_09/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"






### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff_09"
    state_topic: "stat/sonoff_09/POWER"
    command_topic: "cmnd/sonoff_09/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
    availability_topic: "tele/sonoff_09/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
