##############################################################
### Packages / sonoff3                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff3:
      friendly_name: Waschmaschine
      icon: mdi:washing-machine
    sensor.sonoff3_ipv4:
      friendly_name: IPv4 Sonoff 3
      icon: mdi:server-network
    sensor.sonoff3_momentane_leistung:
      friendly_name: Aktuelle Leistung
      icon: mdi:power-plug
    sensor.sonoff3_spannung:
      friendly_name: Spannung
      icon: mdi:flash
    sensor.sonoff3_stromstaerke:
      friendly_name: Stromstärke
      icon: mdi:flash
    sensor.sonoff3_max_load:
      friendly_name: Maximale Leistung
      icon: mdi:fire
    sensor.sonoff3_kosten_heute:
      friendly_name: Kosten Heute
      icon: mdi:currency-eur
    sensor.sonoff3_kosten_gestern:
      friendly_name: Kosten Gestern
      icon: mdi:currency-eur
    sensor.sonoff3_kosten_gesamt:
      friendly_name: Gesamtkosten
      icon: mdi:currency-eur
    sensor.sonoff3_verbrauch_heute:
      friendly_name: Vebrauch Heute
      icon: mdi:chart-line
    sensor.sonoff3_verbrauch_gestern:
      friendly_name: Vebrauch Gestern
      icon: mdi:chart-line
    sensor.sonoff3_gesamtverbrauch:
      friendly_name: Gesamtverbrauch
      icon: mdi:chart-line
    sensor.sonoff3_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast
    script.del_sonoff3_power_log:
      friendly_name: Maximale Leistung zurücksetzen
      icon: mdi:eraser
    automation.washer_start:
      friendly_name: Waschvorgang begonnen
      icon: mdi:washing-machine
    automation.washer_done:
      friendly_name: Benachrichtigung Waschvorgang beendet
      icon: mdi:washing-machine
    input_boolean.washer_switch:
      friendly_name: Waschvorgang aktiv?


sensor:

### Reading the values from the tasmota mqtt string

  - platform: mqtt
    name: "sonoff3 Verbrauch Heute"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 Verbrauch Gestern"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 Gesamtverbrauch"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 Momentane Leistung"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 Spannung"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 Stromstaerke"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: "A"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 uptime"
    state_topic: "tele/sonoff3/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
### Calculating cost based on the local prive per kWh

  - platform: template
    sensors:
      sonoff3_kosten_heute:
        friendly_name: Kosten Heute
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff3_verbrauch_heute.state  | multiply(0.2657) | round(2) }}

      sonoff3_kosten_gestern:
        friendly_name: Kosten Gestern
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff3_verbrauch_gestern.state  | multiply(0.2657) | round(2) }}

      sonoff3_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff3_gesamtverbrauch.state  | multiply(0.2657) | round(2) }}

### Usage sensor for other scripts/automations

      sonoff3_use:
        friendly_name: "Vebraucher aktiv?"
        value_template: "{% if states('sensor.sonoff3_momentane_leistung') | int > 30 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.sonoff3_momentane_leistung') | int > 30 %}mdi:flash{% else %}mdi:flash-off{% endif %}"


### Reading the highest value in the power log file ( see automation)

  - platform: command_line
    name: 'sonoff3_max_load'
    command: "grep -E '[0-9]+' /home/homeassistant/log/sonoff3/power.txt| sort -rn | head -n 1"
    unit_of_measurement: "W"
    scan_interval: 15

### log power to the logfile

notify:
    - name: sonoff3_power_log
      platform: file
      filename: /home/homeassistant/log/sonoff3/power.txt

### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff3"
    state_topic: "stat/sonoff3/POWER1"
    command_topic: "cmnd/sonoff3/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

### Input boolen for washing state and notification

input_boolean:
  washer_switch:
    initial: off
  washer_notify_traude:
    initial: on
  washer_notify_christoph:
    initial: on

### Record all power levels to a file (see notify)
automation:
  - alias: sonoff3 Load logfile
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff3_momentane_leistung
    action:
      - service: notify.sonoff3_power_log
        data_template:
          message: >
            {{ states.sensor.sonoff3_momentane_leistung.state }}

### Notification when Washer is done
  - alias: 'Washer_Start'
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff3_use
        from: 'Nein'
        to: 'Ja'
        for:
          minutes: 2
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.washer_switch

  - alias: 'Washer_Done'
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff3_use
        from: 'Ja'
        to: 'Nein'
        for:
          minutes: 5
    condition:
        condition: state
        entity_id: input_boolean.washer_switch
        state: 'on'
    action:
      - service: notify.pushbullet
        data_template:
          message: "{{ now().strftime('%d.%m.%Y %H:%M:%S') }}:Die Waschmaschine verbraucht keinen Strom mehr."
      - service: notify.pushbullet_traude
        data_template:
          message: "{{ now().strftime('%d.%m.%Y %H:%M:%S') }}:Die Waschmaschine verbraucht keinen Strom mehr."
      - service: input_boolean.turn_off
        entity_id: input_boolean.washer_switch

### Delete the logfile (reset the maximum power sensor)

script:
  del_sonoff3_power_log:
     sequence:
       - service: shell_command.del_sonoff3_power_log

shell_command:
  del_sonoff3_power_log: rm /home/homeassistant/log/sonoff3/power.txt && touch /home/homeassistant/log/sonoff3/power.txt && chown -R -v homeassistant:homeassistant /home/homeassistant/log/sonoff3/power.txt
