##############################################################
### Packages / sonoff06                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff06:
      friendly_name: MPD
      icon: mdi:power-socket-eu
    sensor.sonoff06_ipv4:
      friendly_name: IPv4 Sonoff 6
      icon: mdi:server-network
    sensor.sonoff06_momentane_leistung:
      friendly_name: Aktuelle Leistung
      icon: mdi:power-plug
    sensor.sonoff06_spannung:
      friendly_name: Spannung
      icon: mdi:flash
    sensor.sonoff06_stromstaerke:
      friendly_name: Stromstärke
      icon: mdi:flash
    sensor.sonoff06_max_load:
      friendly_name: Maximale Leistung
      icon: mdi:fire
    sensor.sonoff06_kosten_heute:
      friendly_name: Kosten Heute
      icon: mdi:currency-eur
    sensor.sonoff06_kosten_gestern:
      friendly_name: Kosten Gestern
      icon: mdi:currency-eur
    sensor.sonoff06_kosten_gesamt:
      friendly_name: Gesamtkosten
      icon: mdi:currency-eur
    sensor.sonoff06_verbrauch_heute:
      friendly_name: Vebrauch Heute
      icon: mdi:chart-line
    sensor.sonoff06_verbrauch_gestern:
      friendly_name: Vebrauch Gestern
      icon: mdi:chart-line
    sensor.sonoff06_gesamtverbrauch:
      friendly_name: Gesamtverbrauch
      icon: mdi:chart-line
    sensor.sonoff06_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast
    script.del_sonoff06_power_log:
      friendly_name: Maximale Leistung zurücksetzen
      icon: mdi:eraser





sensor:

### Reading the values from the tasmota mqtt string

  - platform: mqtt
    name: "sonoff06 Verbrauch Heute"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 Verbrauch Gestern"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 Gesamtverbrauch"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 Momentane Leistung"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 Spannung"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 Stromstaerke"
    state_topic: "tele/sonoff06/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: "A"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff06 uptime"
    state_topic: "tele/sonoff06/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff06/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

### Calculating cost based on the local prive per kWh

  - platform: template
    sensors:
      sonoff06_kosten_heute:
        friendly_name: Kosten Heute
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff06_verbrauch_heute.state  | multiply(0.2657) | round(2) }}

      sonoff06_kosten_gestern:
        friendly_name: Kosten Gestern
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff06_verbrauch_gestern.state  | multiply(0.2657) | round(2) }}

      sonoff06_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{states('sensor.sonoff06_gesamtverbrauch') | multiply(0.2657) | round(2) }}

### Usage sensor for other scripts/automations

      sonoff06_use:
        friendly_name: "Vebraucher aktiv?"
        value_template: "{% if states('sensor.sonoff06_momentane_leistung') | int > 3 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.sonoff06_momentane_leistung') | int > 3 %}mdi:flash{% else %}mdi:flash-off{% endif %}"


### Reading the highest value in the power log file ( see automation)

  - platform: command_line
    name: 'sonoff06_max_load'
    command: "grep -E '[0-9]+' /home/homeassistant/log/sonoff06/power.txt| sort -rn | head -n 1"
    unit_of_measurement: "W"
    scan_interval: 15

### log power to the logfile

notify:
    - name: sonoff06_power_log
      platform: file
      filename: /home/homeassistant/log/sonoff06/power.txt

### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff06"
    state_topic: "stat/sonoff06/POWER"
    command_topic: "cmnd/sonoff06/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false



### Record all power levels to a file (see notify)
automation:
  - alias: sonoff06 Load logfile
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff06_momentane_leistung
    mode: queued
    action:
      - service: notify.sonoff06_power_log
        data_template:
          message: >
            {{ states.sensor.sonoff06_momentane_leistung.state }}
  - alias: "Akkuladeautomatik"
    initial_state: False
    trigger:
      - platform: numeric_state
        entity_id: sensor.sonoff06_momentane_leistung
        below: 1
    action:
      - service: notify.pushbullet
        data:
          message: '{{ states.sensor.date_time.state }} Das Ladegerät verbaucht keinen Strom mehr und die Steckdose wurde ausgeschaltet!'
      - service: switch.turn_off
        entity_id: switch.sonoff06
      - service: automation.turn_off
        entity_id: automation.akkuladeautomatik
      - service: persistent_notification.dismiss
        data:
          notification_id: lion_charge



### Delete the logfile (reset the maximum power sensor)

script:
  del_sonoff06_power_log:
     sequence:
       - service: shell_command.del_sonoff06_power_log
  akkus_laden:
    alias: "Akkuladeautomatik"
    sequence:
     - service: automation.turn_on
       entity_id: automation.akkuladeautomatik
     - service: switch.turn_on
       entity_id: switch.sonoff06
     - service: persistent_notification.create
       data:
         message: '{{ states.sensor.date_time.state }} Abschaltautomatikprogramm Akkuladegerät gestartet.'
         title: "Akkuladegerät 18650"
         notification_id: "lion_charge"
shell_command:
  del_sonoff06_power_log: rm /home/homeassistant/log/sonoff06/power.txt && touch /home/homeassistant/log/sonoff06/power.txt && chown -R -v homeassistant:homeassistant /home/homeassistant/log/sonoff06/power.txt
