##############################################################
### Packages / sonoff4                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff4:
      friendly_name: "Server & Router"
      icon: mdi:led-on
    sensor.sonoff4_ipv4:
      friendly_name: IPv4 Sonoff 4
      icon: mdi:server-network
    sensor.sonoff4_momentane_leistung:
      friendly_name: Aktuelle Leistung
      icon: mdi:power-plug
    sensor.sonoff4_spannung:
      friendly_name: Spannung
      icon: mdi:flash
    sensor.sonoff4_stromstaerke:
      friendly_name: Stromstärke
      icon: mdi:flash
    sensor.sonoff4_max_load:
      friendly_name: Maximale Leistung
      icon: mdi:fire
    sensor.sonoff4_kosten_heute:
      friendly_name: Kosten Heute
      icon: mdi:currency-eur
    sensor.sonoff4_kosten_gestern:
      friendly_name: Kosten Gestern
      icon: mdi:currency-eur
    sensor.sonoff4_kosten_gesamt:
      friendly_name: Gesamtkosten
      icon: mdi:currency-eur
    sensor.sonoff4_verbrauch_heute:
      friendly_name: Vebrauch Heute
      icon: mdi:chart-line
    sensor.sonoff4_verbrauch_gestern:
      friendly_name: Vebrauch Gestern
      icon: mdi:chart-line
    sensor.sonoff4_gesamtverbrauch:
      friendly_name: Gesamtverbrauch
      icon: mdi:chart-line
    sensor.sonoff4_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast
    script.del_sonoff4_power_log:
      friendly_name: Maximale Leistung zurücksetzen
      icon: mdi:eraser

group:
  sonoff4:
    control: hidden
    name: Sonoff 4
    view: no
    entities:
      - switch.sonoff4
      - sensor.sonoff4_ipv4
      - sensor.sonoff4_uptime
      - sensor.sonoff4_use
      - sensor.sonoff4_momentane_leistung
      - sensor.sonoff4_spannung
      - sensor.sonoff4_stromstaerke
      - sensor.sonoff4_max_load
      - sensor.sonoff4_verbrauch_heute
      - sensor.sonoff4_verbrauch_gestern
      - sensor.sonoff4_gesamtverbrauch
      - sensor.sonoff4_kosten_heute
      - sensor.sonoff4_kosten_gestern
      - sensor.sonoff4_kosten_gesamt
      - automation.sonoff4_load_lcd
      - script.del_sonoff4_power_log

sensor:

### Reading the values from the tasmota mqtt string
  - platform: mqtt
    name: "sonoff4 Momentane Leistung"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 Verbrauch Heute"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 Verbrauch Gestern"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 Gesamtverbrauch"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 Spannung"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 Stromstaerke"
    state_topic: "tele/sonoff4/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: "A"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 uptime"
    state_topic: "tele/sonoff4/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

### Calculating cost based on the local prive per kWh

  - platform: template
    sensors:
      sonoff4_kosten_heute:
        friendly_name: Kosten Heute
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff4_verbrauch_heute.state  | multiply(0.2657) | round(2) }}

      sonoff4_kosten_gestern:
        friendly_name: Kosten Gestern
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff4_verbrauch_gestern.state  | multiply(0.2657) | round(2) }}

      sonoff4_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff4_gesamtverbrauch.state  | multiply(0.2657) | round(2) }}

### Usage sensor for other scripts/automations

      sonoff4_use:
        friendly_name: "Vebraucher aktiv?"
        value_template: "{% if states('sensor.sonoff4_momentane_leistung') | int > 0.2 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.sonoff4_momentane_leistung') | int > 0.2 %}mdi:flash{% else %}mdi:flash-off{% endif %}"


### Reading the highest value in the power log file ( see automation)

  - platform: command_line
    name: 'sonoff4_max_load'
    command: "grep -E '[0-9]+' /home/homeassistant/log/sonoff4/power.txt| sort -rn | head -n 1"
    unit_of_measurement: "W"
    scan_interval: 15

### log power to the logfile

notify:
    - name: sonoff4_power_log
      platform: file
      filename: /home/homeassistant/log/sonoff4/power.txt

### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff4"
    state_topic: "stat/sonoff4/POWER1"
    command_topic: "cmnd/sonoff4/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false


### Record all power levels to a file (see notify)
automation:
  - alias: sonoff4 Load logfile
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff4_momentane_leistung
    action:
      - service: notify.sonoff4_power_log
        data_template:
          message: >
            {{ states.sensor.sonoff4_momentane_leistung.state }}


### Delete the logfile (reset the maximum power sensor)

script:
  del_sonoff4_power_log:
     sequence:
       - service: shell_command.del_sonoff4_power_log

shell_command:
  del_sonoff4_power_log: rm /home/homeassistant/log/sonoff4/power.txt && touch /home/homeassistant/log/sonoff4/power.txt && chown -R -v homeassistant:homeassistant /home/homeassistant/log/sonoff4/power.txt
