##############################################################
### Packages / sonoff_05                                    ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
#integration
    switch.sonoff_05:
      friendly_name: Trockner
      icon: mdi:tumble-dryer

    sensor.sonoff_05_energy_current:
      friendly_name: Stromstärke
    sensor.sonoff_05_energy_power:
      friendly_name: Leistung
      icon: mdi:power-plug
    sensor.sonoff_05_energy_voltage:
      friendly_name: Spannung

    sensor.sonoff_05_energy_today:
      friendly_name: Verbrauch (Heute)
      icon: mdi:chart-line
    sensor.sonoff_05_energy_yesterday:
      friendly_name: Verbrauch (Gestern)
      icon: mdi:chart-line
    sensor.sonoff_05_energy_total:
      friendly_name: Trockner
      icon: mdi:chart-line



    sensor.sonoff_05_firmware_version:
      friendly_name: "Sonoff #05 Version"
      icon: mdi:counter
    sensor.sonoff_05_ip:
      friendly_name: IPv4
    sensor.sonoff_05_rssi:
      friendly_name: Signalqualität
    sensor.sonoff_05_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast
#template/custom
    sensor.sonoff_05_kosten_heute:
      icon: mdi:currency-eur
    sensor.sonoff_05_kosten_gestern:
      icon: mdi:currency-eur
    sensor.sonoff_05_kosten_gesamt:
      icon: mdi:currency-eur

    sensor.sonoff_05_max_load:
      friendly_name: Max. Leistung
      icon: mdi:fire
    script.del_sonoff_05_power_log:
      friendly_name: Max. Leistung zurücksetzen
      icon: mdi:eraser


sensor:

### uptime sensor
  - platform: mqtt
    name: "sonoff_05_uptime"
    state_topic: "tele/sonoff_05/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff_05/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

### Calculating cost based on the local prive per kWh

  - platform: template
    sensors:
      sonoff_05_kosten_heute:
        friendly_name: Kosten Heute
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff_05_energy_today.state  | multiply(0.2657) | round(2) }}

      sonoff_05_kosten_gestern:
        friendly_name: Kosten Gestern
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff_05_energy_yesterday.state  | multiply(0.2657) | round(2) }}

      sonoff_05_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{ states('sensor.sonoff_05_energy_total')  | multiply(0.2657) | round(2) }}

      sonoff_05_kosten_gesamt_startzeit:
        friendly_name: Gesamtkosten
        value_template: >-
          {{ as_timestamp(states('sensor.sonoff_05_energy_totalstarttime')) | timestamp_custom('%d.%m.%y') }}
### Usage sensor for other scripts/automations

      sonoff_05_use:
        friendly_name: "Vebraucher aktiv?"
        value_template: "{% if states('sensor.sonoff_05_energy_power') | int > 1 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.sonoff_05_energy_power') | int > 1 %}mdi:flash{% else %}mdi:flash-off{% endif %}"


### Reading the highest value in the power log file ( see automation)

  - platform: command_line
    name: 'sonoff_05_max_load'
    command: "grep -E '[0-9]+' /home/homeassistant/log/sonoff_05/power.txt| sort -rn | head -n 1"
    unit_of_measurement: "W"
    scan_interval: 15

### log power to the logfile

notify:
    - name: sonoff_05_power_log
      platform: file
      filename: /home/homeassistant/log/sonoff_05/power.txt




### Record all power levels to a file (see notify)
automation:
  - alias: sonoff_05 Load logfile
    initial_state: True
    trigger:
      - platform: state

        entity_id: sensor.sonoff_05_energy_power
    mode: queued
    action:
      - service: notify.sonoff_05_power_log
        data_template:
          message: >
            {{ states.sensor.sonoff_05_energy_power.state }}





### Delete the logfile (reset the maximum power sensor)

script:
  del_sonoff_05_power_log:
     sequence:
       - service: shell_command.del_sonoff_05_power_log


shell_command:
  del_sonoff_05_power_log: rm /home/homeassistant/log/sonoff_05/power.txt && touch /home/homeassistant/log/sonoff_05/power.txt && chown -R -v homeassistant:homeassistant /home/homeassistant/log/sonoff_05/power.txt
