##############################################################
### Packages / sonoff_11                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff_11:
      friendly_name: "Esszimmer Fenster"
      icon: mdi:lamp
    sensor.sonoff_11_ipv4:
      friendly_name: IPv4 Sonoff 11
      icon: mdi:server-network
    sensor.sonoff_11_uptime:
      friendly_name: Laufzeit
      icon: mdi:clock-fast



sensor:

### Reading the values from the tasmota mqtt string



  - platform: mqtt
    name: "sonoff_11 uptime"
    state_topic: "tele/sonoff_11/STATE"
    value_template: "{{ value_json.Uptime }}"
    availability_topic: "tele/sonoff_11/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"





### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff_11"
    state_topic: "stat/sonoff_11/POWER"
    command_topic: "cmnd/sonoff_11/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
    availability_topic: "tele/sonoff_11/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
