##############################################################
### Packages / Update_Sonoff_Status                        ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd & sjabby                                ###
### https://github.com/cnrd / https://github.com/sjabby    ###
##############################################################
homeassistant:
  customize:

    sensor.sonoff1_sw_version:
      friendly_name: "Sonoff #1 Version"
      icon: mdi:counter
    sensor.sonoff2_sw_version:
      friendly_name: "Sonoff #2 Version"
      icon: mdi:counter
    sensor.sonoff3_sw_version:
      friendly_name: "Sonoff #3 Version"
      icon: mdi:counter
    sensor.sonoff4_sw_version:
      friendly_name: "Sonoff #4 Version"
      icon: mdi:counter
    sensor.sonoff5_sw_version:
      friendly_name: "Sonoff #5 Version"
      icon: mdi:counter
    sensor.sonoff6_sw_version:
      friendly_name: "Sonoff #6 Version"
      icon: mdi:counter
    sensor.sonoff7_sw_version:
      friendly_name: "Sonoff #7 Version"
      icon: mdi:counter
    sensor.sonoff8_sw_version:
      friendly_name: "Sonoff #8 Version"
      icon: mdi:counter
#group file for auto-entity filter
group:
  sonoff_sw_version:
    entities:
      - sensor.sonoff1_sw_version
      - sensor.sonoff2_sw_version
      - sensor.sonoff3_sw_version
      - sensor.sonoff4_sw_version
      - sensor.sonoff5_sw_version
      - sensor.sonoff6_sw_version
      - sensor.sonoff7_sw_version
      - sensor.sonoff8_sw_version

#get alle sonoff information upon hass boot
automation:
    - alias: get_sonoff_info
      trigger:
        platform: homeassistant
        event: start
      action:
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/Status"
            payload: "5"
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/Status"
            payload: "2"
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/state"
            payload: ""
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER2
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER3
#notification for new release
    - alias: tasmota_update_notification
      initial_state: True
      trigger:
        - platform: state
          entity_id: sensor.sonoff_latest_release
      condition:
        condition: and
        conditions:
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != 'unavailable' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != 'unaailable' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != '' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff1_sw_version') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff1_sw_version') != '' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != states('sensor.sonoff1_sw_version')}}"
      action:
        - service: notify.pushbullet
          data_template:
            message: "Es gibt eine neue Tasmota Version! Tasmota {{ states('sensor.sonoff_latest_release') }}."
        - service: persistent_notification.create
          data:
            title: "Tasmota Update"
            message: "Es gibt eine neue Tasmota Version! {{ states('sensor.sonoff_latest_release') }}. - {{ as_timestamp(now()) | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}"
            notification_id: "tasmota_update"
#update manually
script:
  update_update_sonoff_info:
    sequence:
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/Status"
            payload: "5"
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/Status"
            payload: "2"
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/state"
            payload: ""
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER2
        - service: mqtt.publish
          data:
            topic: cmnd/sonoffs/POWER3

#binary_sensor for every device
binary_sensor:
  - platform: mqtt
    name: sonoff1_state
    state_topic: "tele/sonoff1/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff2_state
    state_topic: "tele/sonoff2/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff3_state
    state_topic: "tele/sonoff3/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff4_state
    state_topic: "tele/sonoff4/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff5_state
    state_topic: "tele/sonoff5/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff6_state
    state_topic: "tele/sonoff6/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff7_state
    state_topic: "tele/sonoff7/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff8_state
    state_topic: "tele/sonoff8/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity


  #Latest Release
sensor:
  - platform: rest
    name: sonoff_latest_release_raw
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    username: !secret github_user
    password: !secret github_token
    authentication: basic
    value_template: '{{ value_json.tag_name  }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: template
    sensors:
      sonoff_latest_release:
        value_template: >-
          {{ states.sensor.sonoff_latest_release_raw.state |replace ('v','')  }}

  #ipv4 sonoff
  - platform: mqtt
    name: "sonoff1 IPv4"
    state_topic: "stat/sonoff1/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff2 IPv4"
    state_topic: "stat/sonoff2/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 IPv4"
    state_topic: "stat/sonoff3/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 IPv4"
    state_topic: "stat/sonoff4/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff5 IPv4"
    state_topic: "stat/sonoff5/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff6 IPv4"
    state_topic: "stat/sonoff6/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff6/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff7 IPv4"
    state_topic: "stat/sonoff7/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff7/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff8 IPv4"
    state_topic: "stat/sonoff8/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff8/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  #SW Version

  - platform: mqtt
    name: "sonoff1 sw version"
    state_topic: "stat/sonoff1/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version |replace ('(release-sonoff)','')  }}"
    availability_topic: "tele/sonoff1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff2 sw version"
    state_topic: "stat/sonoff1/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version |replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff3 sw version"
    state_topic: "stat/sonoff3/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','')  }}"
    availability_topic: "tele/sonoff3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff4 sw version"
    state_topic: "stat/sonoff4/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff5 sw version"
    state_topic: "stat/sonoff5/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff6 sw version"
    state_topic: "stat/sonoff6/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff6/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff7 sw version"
    state_topic: "stat/sonoff7/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff7/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff8 sw version"
    state_topic: "stat/sonoff8/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(release-sonoff)','') }}"
    availability_topic: "tele/sonoff8/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

