##############################################################
### Packages / Update_Sonoff_Status                        ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd & sjabby                                ###
### https://github.com/cnrd / https://github.com/sjabby    ###
##############################################################
homeassistant:
  customize:
    sensor.sonoff_01_sw_version:
      friendly_name: "Sonoff #01 Version"
      icon: mdi:counter
    sensor.sonoff_02_sw_version:
      friendly_name: "Sonoff #02 Version"
      icon: mdi:counter
    sensor.sonoff_03_sw_version:
      friendly_name: "Sonoff #03 Version"
      icon: mdi:counter
    sensor.sonoff_04_sw_version:
      friendly_name: "Sonoff #04 Version"
      icon: mdi:counter
    sensor.sonoff_05_sw_version:
      friendly_name: "Sonoff #05 Version"
      icon: mdi:counter
    sensor.sonoff_06_sw_version:
      friendly_name: "Sonoff #06 Version"
      icon: mdi:counter
    sensor.sonoff_07_sw_version:
      friendly_name: "Sonoff #07 Version"
      icon: mdi:counter
    sensor.sonoff_08_sw_version:
      friendly_name: "Sonoff #08 Version"
      icon: mdi:counter
    sensor.sonoff_09_sw_version:
      friendly_name: "Sonoff #09 Version"
      icon: mdi:counter
    sensor.sonoff_10_sw_version:
      friendly_name: "Sonoff #10 Version"
      icon: mdi:counter
    sensor.sonoff_11_sw_version:
      friendly_name: "Sonoff #11 Version"
      icon: mdi:counter
    sensor.sonoff_12_sw_version:
      friendly_name: "Sonoff #12 Version"
      icon: mdi:counter
    sensor.sonoff_13_sw_version:
      friendly_name: "Sonoff #13 Version"
      icon: mdi:counter
#group file for auto-entity filter
group:
  sonoff_sw_version:
    entities:
      - sensor.sonoff_01_sw_version
      - sensor.sonoff_02_sw_version
      - sensor.sonoff_03_sw_version
      - sensor.sonoff_04_sw_version
      - sensor.sonoff_05_sw_version
      - sensor.sonoff_06_sw_version
      - sensor.sonoff_07_sw_version
      - sensor.sonoff_08_sw_version
      - sensor.sonoff_09_sw_version
      - sensor.sonoff_10_sw_version
      - sensor.sonoff_11_sw_version
      - sensor.sonoff_12_sw_version
      - sensor.sonoff_13_sw_version

#get alle sonoff information upon hass boot
automation:
    - alias: "Tasmota State on HA Restart"
      trigger:
        platform: homeassistant
        event: start
      action:
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/backlog"
            payload: "status 0; power"

#get sonoff info when device is Online

    - alias: "sonoff_online_state_request"
      trigger:
        platform: state
        entity_id:
          - binary_sensor.switch_sonoff_sonoff_01
          - binary_sensor.switch_sonoff_sonoff_02
          - binary_sensor.switch_sonoff_sonoff_03
          - binary_sensor.switch_sonoff_sonoff_04
          - binary_sensor.switch_sonoff_sonoff_05
          - binary_sensor.switch_sonoff_sonoff_06
          - binary_sensor.switch_sonoff_sonoff_07
          - binary_sensor.switch_sonoff_sonoff_08
          - binary_sensor.switch_sonoff_sonoff_09
          - binary_sensor.switch_sonoff_sonoff_10
          - binary_sensor.switch_sonoff_sonoff_11
          - binary_sensor.switch_sonoff_sonoff_12
          - binary_sensor.switch_sonoff_sonoff_13
        from: 'off'
        to: 'on'
      mode: queued
      action:
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/backlog"
            payload: "status 0; power"


#notification for new release
    - alias: tasmota_update_notification
      initial_state: True
      trigger:
        - platform: state
          entity_id: sensor.sonoff_latest_release
      condition:
        condition: and
        conditions:
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != 'unavailable' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != 'unaailable' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release_raw') != '' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_01_sw_version') != 'unknown' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_01_sw_version') != '' }}"
            - condition: template
              value_template: "{{ states('sensor.sonoff_latest_release') != states('sensor.sonoff_01_sw_version')}}"
      action:
        - service: notify.pushbullet
          data_template:
            message: "Es gibt eine neue Tasmota Version! Tasmota {{ states('sensor.sonoff_latest_release') }}."
        - service: persistent_notification.create
          data:
            title: "Tasmota Update"
            message: "Es gibt eine neue Tasmota Version! {{ states('sensor.sonoff_latest_release') }}. - {{ as_timestamp(now()) | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}"
            notification_id: "tasmota_update"
#update manually
script:
  update_update_sonoff_info:
    sequence:
        - service: mqtt.publish
          data:
            topic: "cmnd/sonoffs/backlog"
            payload: "status 0;power "
#binary_sensor for every device
binary_sensor:
  - platform: mqtt
    name: sonoff_01_state
    state_topic: "tele/sonoff_01/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_02_state
    state_topic: "tele/sonoff_02/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_03_state
    state_topic: "tele/sonoff_03/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_04_state
    state_topic: "tele/sonoff_04/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_05_state
    state_topic: "tele/sonoff_05/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_06_state
    state_topic: "tele/sonoff_06/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_07_state
    state_topic: "tele/sonoff_07/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_08_state
    state_topic: "tele/sonoff_08/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_09_state
    state_topic: "tele/sonoff_09/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_10_state
    state_topic: "tele/sonoff_10/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_11_state
    state_topic: "tele/sonoff_11/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_12_state
    state_topic: "tele/sonoff_12/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: sonoff_13_state
    state_topic: "tele/sonoff_13/LWT"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity


  #Latest Release
sensor:
  - platform: rest
    name: sonoff_latest_release_raw
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    username: !secret github_user
    password: !secret github_token
    authentication: basic
    value_template: '{{ value_json.tag_name  }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: template
    sensors:
      sonoff_latest_release:
        value_template: >-
          {{ states('sensor.sonoff_latest_release_raw') |replace ('v','')  }}
  - platform: template
    sensors:
      sonoff_01_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_01_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_02_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_02_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_03_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_03_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_04_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_04_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_05_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_05_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_06_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_06_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_07_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_07_firmware_version')|replace ('(tasmota)','')  }}
  - platform: template
    sensors:
      sonoff_08_firmware_version:
        value_template: >-
          {{ states('sensor.sonoff_08_firmware_version')|replace ('(tasmota)','')  }}






  - platform: mqtt
    name: "sonoff_09 IPv4"
    state_topic: "stat/sonoff_09/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff_09/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_10 IPv4"
    state_topic: "stat/sonoff_10/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff_10/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_11 IPv4"
    state_topic: "stat/sonoff_11/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff_11/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_12 IPv4"
    state_topic: "stat/sonoff_12/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff_12/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_13 IPv4"
    state_topic: "stat/sonoff_13/STATUS5"
    value_template: "{{ value_json.StatusNET.IPAddress }}"
    availability_topic: "tele/sonoff_13/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  #SW Version



  - platform: mqtt
    name: "sonoff_09 sw version"
    state_topic: "stat/sonoff_09/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(tasmota)','') }}"
    availability_topic: "tele/sonoff_09/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_10 sw version"
    state_topic: "stat/sonoff_10/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(tasmota)','') }}"
    availability_topic: "tele/sonoff_10/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_11 sw version"
    state_topic: "stat/sonoff_11/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(tasmota)','') }}"
    availability_topic: "tele/sonoff_11/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_12 sw version"
    state_topic: "stat/sonoff_12/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(tasmota)','') }}"
    availability_topic: "tele/sonoff_12/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "sonoff_13 sw version"
    state_topic: "stat/sonoff_13/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version|replace ('(tasmota)','') }}"
    availability_topic: "tele/sonoff_13/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
