########################################################################
## Packages / ESP32 #2                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:
    sensor.esp32_02_humidity:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit Haupteingang

    sensor.esp32_02_temperature:
      icon: mdi:thermometer
      friendly_name: Temperatur Haupteingang

    sensor.esp32_02_pressure:
      icon: mdi:gauge
      friendly_name: Luftdruck Haupteingang

    sensor.esp32_02_rssi:
      icon: mdi:wifi
      friendly_name: "ESP32 #2 Signalstärke"

    sensor.esp32_02_temperature_last_changed:
      icon: mdi:delta
      friendly_name: Letzte Änderung





#############
#  sensors  #
#############
sensor:

#bme280 values
  - platform: mqtt
    name: "esp32_02_humidity"
    state_topic: "esp32_2/sensor/humidity/state"
    qos: 0
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    name: "esp32_02_temperature"
    state_topic: "esp32_2/sensor/temperature/state"
    qos: 0
    unit_of_measurement: "°C"
    force_update: true

  - platform: mqtt
    name: "esp32_02_pressure"
    state_topic: "esp32_2/sensor/pressure/state"
    qos: 0
    unit_of_measurement: "hPa"
    force_update: true
#wifi signal strength
  - platform: mqtt
    name: "esp32_02_rssi"
    state_topic: "esp32_2/sensor/esp32_2_wifi_signal_sensor/state"
    qos: 0
    unit_of_measurement: "dB"
#battery value
  - platform: mqtt
    name: "esp32_02_battery"
    state_topic: "esp32_2/sensor/spannung_akku/state"
    unit_of_measurement: "V"
    qos: 0
    force_update: true
# temp last changed
  - platform: template
    sensors:
      esp32_02_temperature_last_changed:
        value_template: >-
          {{ as_timestamp(states.sensor.esp32_02_temperature.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

#############
#  switch   #
#############
switch:

  - platform: mqtt
    name: ESP32_2 Shutdown
    state_topic: esp32_2/switch/esp32_2_shutdown/state
    command_topic: esp32_2/switch/esp32_2_shutdown/command
