########################################################################
## Packages / ESP32 #4                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:


input_number:
  light_serverroom:
    name: Brenndauer?
    initial: 30
    min: 10
    max: 240
    step: 10





automation:
  - id: turn_on_light_serverroom_when_home
    alias: turn_on_light_serverroom_when_home
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.esp32_04_motion', 'on') }}"
    condition:
      - condition: template
        value_template: "{{ is_state('input_boolean.chrishome', 'on') }}"
      - condition: template
        value_template: "{{ is_state('switch.sonoff13', 'off') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.esp32_04_led
      - service: switch.turn_on
        data:
          entity_id: switch.sonoff13

  - id: turn_off_light_serverroom_when_home
    alias: turn_off_light_serverroom_when_home
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.esp32_04_motion', 'off') }}"
        for:
          seconds: "{{ states('input_number.light_serverroom')|int }}"
    condition:
      - condition: template
        value_template: "{{ is_state('switch.sonoff13', 'on') }}"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.esp32_04_led
      - service: switch.turn_off
        data:
          entity_id: switch.sonoff13
