########################################################################
## Packages / ESP32 #4                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:


input_number:
  light_serverroom:
    name: Brenndauer?
    initial: 30
    min: 10
    max: 240
    step: 10


#############
#  sensors  #
#############
sensor:
  - platform: template
    sensors:

      esp32_4_uptime_format:
        friendly_name: Uptime
        value_template: >-
           {% if states('binary_sensor.esp32_4_status') | lower == "off" %}
             Node offline
           {% else %}
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}

              {%- set weeks = seconds // intervals.weeks -%}
              {%- set seconds = seconds % intervals.weeks -%}
              {{- comma() ~ weeks ~ 'w' if weeks -}}

              {%- set days = seconds // intervals.days -%}
              {%- set seconds = seconds % intervals.days -%}
              {{- comma() ~ days ~ 'd' if days -}}

              {%- set hours = seconds // intervals.hours -%}
              {%- set seconds = seconds % intervals.hours -%}
              {{- comma() ~ hours ~ 'h' if hours -}}

              {%- set minutes = seconds // intervals.minutes -%}
              {{- comma() ~ minutes ~ 'm' if minutes -}}

              {%- set seconds = seconds % intervals.minutes -%}
              {{- comma() ~ seconds ~ 's' if seconds -}}
            {%- endmacro %}
            {{ human_time(states.sensor.esp32_4_uptime.state | int   ) }}
            {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.esp32_4_status', 'on') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}


automation:
  - id: turn_on_light_serverroom_when_home
    alias: turn_on_light_serverroom_when_home
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.esp32_4_motion', 'on') }}"
    condition:
      - condition: template
        value_template: "{{ is_state('input_boolean.chrishome', 'on') }}"
      - condition: template
        value_template: "{{ is_state('switch.sonoff8', 'off') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.esp32_4_led
      - service: switch.turn_on
        data:
          entity_id: switch.sonoff8

  - id: turn_off_light_serverroom_when_home
    alias: turn_off_light_serverroom_when_home
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.esp32_4_motion', 'off') }}"
        for:
          seconds: "{{ states('input_number.light_serverroom')|int }}"
    condition:
      - condition: template
        value_template: "{{ is_state('switch.sonoff8', 'on') }}"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.esp32_4_led
      - service: switch.turn_off
        data:
          entity_id: switch.sonoff8
