########################################################################
## Packages / ESP32 #4                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:

    binary_sensor.esp32_04_door_state:
      friendly_name: Briefkasten
    sensor.esp32_04_battery:
      icon: mdi:car-battery
      friendly_name: Batteriewert ESP32_04

    sensor.esp32_04_battery_state:
      icon: mdi:car-battery
      friendly_name: Batteriestatus ESP32_04


    sensor.esp32_04_rssi:
      icon: mdi:wifi
      friendly_name: "ESP32_04 Signalstärke"

    sensor.esp32_04_motion_last_changed:
      icon: mdi:delta
      friendly_name: Letzte Änderung

    automation.benachrichtigung_batterie_esp32_04:
      icon: mdi:power-socket-eu
      friendly_name: Akkuwarnung


#############
#  group    #
#############
group:

  esp32_04:
    control: hidden
    icon: mdi:mailbox
    name: Briefkasten
    entities:
      - binary_sensor.esp32_04_door_state
      - sensor.esp32_04_rssi
      - sensor.esp32_04_battery
      - sensor.esp32_04_battery_state
      - sensor.esp32_04_motion_last_changed
      - automation.benachrichtigung_batterie_esp32_04
      - automation.postbenachrichtigung
  esp32_04_short:
    control: hidden
    icon: mdi:door
    name: Briefkasten
    entities:
      - binary_sensor.esp32_04_door_state
      - sensor.esp32_04_motion_last_changed


#############
#  sensors  #
#############
binary_sensor:
  - platform: mqtt
    name: esp32_04_door_state
    state_topic: "esp32_4/binary_sensor/door/state"
    device_class: door

sensor:
  - platform: mqtt
    name: "esp32_04_battery"
    state_topic: "esp32_4/sensor/spannung_akku/state"
    unit_of_measurement: "V"
    qos: 0

  - platform: mqtt
    name: "esp32_04_rssi"
    state_topic: "esp32_4/sensor/esp32_4_wifi_signal_sensor/state"
    qos: 0
    unit_of_measurement: "dB"


  - platform: template
    sensors:

      esp32_04_door_motion:
        value_template: '{% if is_state("sensor.esp32_04_door_state", "ON") %}Briefkasten geöffnet!{% else %}Briefkasten geschlossen.{% endif %}'
        icon_template: '{% if is_state("sensor.esp32_04_door_state", "ON") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'

      esp32_04_battery_state:
        value_template: "{{ 'Geladen' if states.sensor.esp32_04_battery.state | float >3.3  else 'Leer' }}"
        icon_template: "{{ 'mdi:battery' if states.sensor.esp32_04_battery.state | float >3.3  else 'mdi:battery-10' }}"

      esp32_04_motion_last_changed:
        value_template: >-
          {{ as_timestamp(states.binary_sensor.esp32_04_door_state.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}


### automation battery empty
automation:
  - alias: benachrichtigung_batterie_esp32_04
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: sensor.esp32_04_battery
        below: 3.0
        for:
          seconds: 5
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != nan }}"
    action:
      - service: notify.pushbullet
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
      - service: persistent_notification.create
        data_template:
          title: "{{ trigger.to_state.attributes.friendly_name }}"
          message: >
              {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
          notification_id: "esp04_battery_notification"


  - alias: postbenachrichtigung
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.esp32_04_door_state
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != nan }}"
    action:
      - service: notify.pushbullet
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Post war da!
      - service: telegram_bot.send_message
        data_template:
          target: !secret telegram_chat_id_christoph
          disable_notification: true
          message: >
             "{{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Post war da!"
