########################################################################
## Packages / ESP32 #1                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:

    binary_sensor.esp32_01_door_state:
      friendly_name: T체re ELW

    binary_sensor.esp32_01_ota_status:
      friendly_name: OTA Mode

    sensor.esp32_01_battery:
      icon: mdi:car-battery
      friendly_name: Batteriewert ESP32 01

    sensor.esp32_01_battery_state:
      icon: mdi:car-battery
      friendly_name: Batteriestatus ESP32 01


    sensor.esp32_01_rssi:
      icon: mdi:wifi
      friendly_name: "ESP32 #1 Signalst채rke"


    automation.benachrichtigung_batterie_esp32_01:
      icon: mdi:power-socket-eu
      friendly_name: Akkuwarnung




#############
#  sensors  #
#############
binary_sensor:
  - platform: mqtt
    name: esp32_01_door_state
    state_topic: "esp32_01/binary_sensor/door/state"
    device_class: door

  - platform: mqtt
    name: "esp32_01_status"
    state_topic: "esp32_01/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity

  - platform: mqtt
    name: "esp32_01_ota_status"
    state_topic: "esp32_01/ota_mode_status"
    payload_on: "active"
    payload_off: "disabled"

sensor:
  - platform: mqtt
    name: "esp32_01_battery"
    state_topic: "esp32_01/sensor/esp32_01_voltage/state"
    unit_of_measurement: "V"
    qos: 0

  - platform: mqtt
    name: "esp32_01_rssi"
    state_topic: "esp32_01/sensor/esp32_01_rssi/state"
    qos: 0
    unit_of_measurement: "dB"

  - platform: mqtt
    name: "esp32_01_ip"
    state_topic: "esp32_01/sensor/esp32_01_ip/state"
    qos: 0

  - platform: mqtt
    name: "esp32_01_version"
    icon: mdi:new-box
    state_topic: "esp32_01/sensor/esp32_01_version/state"
    qos: 0

  - platform: mqtt
    name: "esp32_01_wifi_quality"
    unit_of_measurement: "%"
    icon: mdi:wifi
    state_topic: "esp32_01/sensor/esp32_01_wifi_quality/state"
    qos: 0


  - platform: template
    sensors:

      esp32_01_battery_state:
        value_template: "{{ 'Geladen' if states.sensor.esp32_01_battery.state | float >3.3  else 'Leer' }}"
        icon_template: "{{ 'mdi:battery' if states.sensor.esp32_01_battery.state | float >3.3  else 'mdi:battery-10' }}"

      esp32_01_motion_last_changed:
        value_template: >-
          {{ as_timestamp(states.binary_sensor.esp32_01_door_state.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

switch:
  - platform: mqtt
    name: "esp32_01_shutdown"
    state_topic: esp32_01/switch/esp32_01_shutdown/state
    command_topic: esp32_01/switch/esp32_01_shutdown/command
    availability_topic: "esp32_01/status"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "online"
    state_off: "offline"

  - platform: mqtt
    name: "esp32_01_restart"
    state_topic: esp32_01/switch/esp32_01_restart/state
    command_topic: esp32_01/switch/esp32_01_restart/command
    availability_topic: "esp32_01/status"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "online"
    state_off: "offline"

  - platform: template
    switches:
      esp32_01_switch_ota:
        value_template: "{{ is_state('binary_sensor.esp32_01_ota_status', 'on') }}"
        turn_on:
          - service: mqtt.publish
            data:
              topic: "esp32_01/ota_mode"
              payload: "ON"
              retain: true
        turn_off:
          - service: mqtt.publish
            data:
              topic: "esp32_01/sleep_mode"
              payload: "ON"
          - service: mqtt.publish
            data:
              topic: "esp32_01/ota_mode"
              payload: ""
              retain: true




### automation battery empty
automation:
  - alias: benachrichtigung_batterie_esp32_01
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: sensor.esp32_01_battery
        below: 3.0
        for:
          seconds: 5
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != nan }}"
    action:
      - service: notify.pushbullet
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
      - service: persistent_notification.create
        data_template:
          title: "{{ trigger.to_state.attributes.friendly_name }}"
          message: >
              {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
          notification_id: "esp01_battery_notification"

  - alias: esp32_01_ota_online
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.esp32_01_status
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: 'binary_sensor.esp32_01_ota_status'
          state: 'on'
    action:
    - service: notify.telegram_christoph
      data_template:
        message: >
          {{ now().strftime('%d.%m.%Y %H:%M:%S') }} ESP #1 Online and in OTA Mode!

  - alias: esp32_01_update_warning
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.esp32_01_status
        to: 'off'
        for:
          minutes: 730
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"

    action:
    - service: notify.telegram_christoph
      data_template:
        message: >
          {{ now().strftime('%d.%m.%Y %H:%M:%S') }} No Update: T체rsensor ELW (ESP #1)!
    - service: notify.sensor_watch_log
      data_template:
        message: >
          {{ now().strftime('%d.%m.%Y %H:%M:%S') }} No Update: T체rsensor ELW (ESP #1)!
