########################################################################
## Packages / ESP32 #3                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:


    sensor.esp32_03_battery:
      icon: mdi:car-battery
      friendly_name: Batteriewert ESP32 03 Carport

    sensor.esp32_03_battery_state:
      icon: mdi:car-battery
      friendly_name: Batteriestatus ESP32 03

    sensor.esp32_03_humidity:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit Carport

    sensor.esp32_03_temperature:
      icon: mdi:thermometer
      friendly_name: Temperatur Carport

    sensor.esp32_03_pressure:
      icon: mdi:gauge
      friendly_name: Luftdruck Carport

    sensor.esp32_03_rssi:
      icon: mdi:wifi
      friendly_name: "ESP32 #3 Signalstärke"


    sensor.esp32_03_temperature_last_changed:
      icon: mdi:delta
      friendly_name: Letzte Änderung

    automation.benachrichtigung_batterie_esp32_03:
      icon: mdi:power-socket-eu
      friendly_name: Akkuwarnung

#############
#  switch   #
#############
switch:
  - platform: mqtt
    name: ESP32_3 Shutdown
    state_topic: esp32_3/switch/esp32_3_shutdown/state
    command_topic: esp32_3/switch/esp32_3_shutdown/command



#############
#  sensors  #
#############
sensor:

  - platform: mqtt
    name: "esp32_03_battery"
    state_topic: "esp32_3/sensor/spannung_akku/state"
    unit_of_measurement: "V"
    qos: 0
    force_update: true

  - platform: mqtt
    name: "esp32_03_humidity"
    state_topic: "esp32_3/sensor/humidity/state"
    qos: 0
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    name: "esp32_03_temperature"
    state_topic: "esp32_3/sensor/temperature/state"
    qos: 0
    unit_of_measurement: "°C"
    force_update: true

  - platform: mqtt
    name: "esp32_03_pressure"
    state_topic: "esp32_3/sensor/pressure/state"
    qos: 0
    unit_of_measurement: "hPa"
    force_update: true

  - platform: mqtt
    name: "esp32_03_rssi"
    state_topic: "esp32_3/sensor/esp32_3_wifi_signal_sensor/state"
    qos: 0
    unit_of_measurement: "dB"
    force_update: true




  - platform: template
    sensors:

      esp32_03_battery_state:
        value_template: "{{ 'Geladen ' if states.sensor.esp32_03_battery.state | float >3.3  else 'Leer' }}"
        icon_template: "{{ 'mdi:battery ' if states.sensor.esp32_03_battery.state | float >3.3  else 'mdi:battery-10' }}"

      esp32_03_temperature_last_changed:
        value_template: >-
          {{ as_timestamp(states.sensor.esp32_03_temperature.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}


### automation battery empty
automation:
  alias: benachrichtigung_batterie_esp32_03
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.esp32_03_battery
      below: 3.3
      for:
        seconds: 5
  action:
    - service: switch.turn_on
      entity_id: switch.esp32_3_shutdown
    - service: notify.pushbullet
      data_template:
        message: >
           {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
    - service: persistent_notification.create
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }}"
        message: >
            {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
        notification_id: "esp02_battery_notification"
