alias: Minimote Button 4 Pressed Long
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 8
action:
  - service: media_player.toggle
    entity_id: media_player.yamaha_receiver
