alias: Minimote Button 3 Pressed Long
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 6
action:
  - service: notify.pushbullet
    data_template:
      title: "button 3 long"
      message: >
         Button 3 long  pressed!  {{ now().strftime('%d.%m.%Y %H:%M:%S') }}