alias: Minimote Button 1 Pressed
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 1
action:
  - service: notify.echodot
    data_template:
      message: >
         Es werde Licht
  - service: scene.turn_on
    entity_id: scene.elw_relax
