alias: Minimote Button 2 Pressed
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 3
action:
  - service: switch.toggle
    entity_id: switch.110011