alias: Minimote Button 3 Pressed
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 5
action:
- service: notify.echodot
  data_template:
    message: >
      {% if now().strftime("%H")|int < 12 %}
      Guten Morgen.
      {% elif now().strftime("%H")|int < 18 %}
      Guten Nachmittag.
      {% else %}
      Guten Abend.
      {% endif %}
      Es hat {{ states('sensor.temperatur_esp8266_02')|round(1)|replace(".", ",") }} Grad in der E L W und die Außentemperatur ist {{ states('sensor.esp32_02_temperature')|round(1)|replace(".", ",") }} Grad. 
      Die Fahrzeit zur Hauptrettungswache beträgt momentan {{ states('sensor.zuhause__hauptrettungswache') }} Minuten.
