alias: Minimote Button 3 Pressed
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 5
action:
- service: tts.amazon_polly_say
  data_template:
    entity_id: media_player.volumio_tts
    message: >
      Die Fahrzeit zur Hauptrettungswache beträgt momentan {{ states('sensor.zuhause__hauptrettungswache') }} Minuten. Tschüß.

