alias: Minimote Button 2 Pressed Long
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 4
action:
  - service: switch.toggle
    entity_id: switch.wemoswitch1