alias: Minimote Button 3 Pressed
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 5
action:
- service: tts.amazon_polly_say
  data_template:
    entity_id: media_player.volumio_tts
    message: >
      {% if now().strftime("%H")|int < 12 %}
      Guten Morgen.
      {% elif now().strftime("%H")|int < 18 %}
      Guten Nachmittag.
      {% else %}
      Guten Abend.
      {% endif %}
      Es hat {{ states('sensor.temperatur_esp8266_02')|round(1)|replace(".", ",") }} Grad in der E L W und die Außentemperatur ist {{ states('sensor.dark_sky_temperature')|round }} Grad. 
      Die Fahrzeit zur Hauptrettungswache beträgt momentan {{ states('sensor.zuhause__hauptrettungswache') }} Minuten.
