alias: Minimote Button 1 Pressed Long
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 2
action:
  - service: notify.echodot
    data_template:
      message: >
         Lichter werden ausgeschaltet
  - service: scene.turn_on
    entity_id: scene.elwaus
