alias: Minimote Button 4 Pressed
initial_state: True
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    node_id: 6
    scene_id: 7
action:
  - service: switch.toggle
    entity_id: switch.receiver_source_pc

