alias: 'MQTT autosshtunnel stop'
initial_state: True
trigger:
  platform: mqtt
  topic: service
  payload: 'stop_autossh'
action:
  - service: homeassistant.turn_off
    entity_id: switch.ssh_tunnel
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }}: Der SSH Tunnel wurde gestoppt'
