################################################################
## Packages / NodeMCU #3
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:

    sensor.esp8266_03:
      entity_picture: /local/esp.jpg

    sensor.temperatur_esp8266_03:
      icon: mdi:thermometer
      friendly_name: Temperatur Wintergarten

    sensor.luftfeuchtigkeit_esp8266_03:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit Wintergarten



###############################################################################
#  Sensors
###############################################################################
binary_sensor:
  - platform: mqtt
    state_topic: "sensor_esp8266_03/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
    name: "sensor_esp8266_03_status_binary"

sensor:

  - platform: mqtt
    name: "Temperatur ESP8266 03"
    state_topic: "sensor_esp8266_03/sensor/temperature/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Luftfeuchtigkeit ESP8266 03"
    state_topic: "sensor_esp8266_03/sensor/humidity/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "ESP8266 03 PIR"
    availability_topic: "sensor_esp8266_03/status"
    state_topic: "sensor_esp8266_03/binary_sensor/motion/state"
    qos: 0

  - platform: mqtt
    name: "ESP8266 03 Signal"
    state_topic: "sensor_esp8266_03/sensor/rssi/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "dB"


  - platform: mqtt
    name: "ESP8266 03 Uptime"
    state_topic: "sensor_esp8266_03/sensor/uptime/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "seconds"

  - platform: template
    sensors:


      esp8266_03_status_var:
        friendly_name: "ESP8266 03 Status"
        value_template: >-
           {%- if is_state('device_tracker.soc_esp8266_03', 'home') -%}
             Online!  Uptime: {{ states.sensor.esp8266_03_uptime_human.state }}
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}
        icon_template: >-
          {% if is_state('device_tracker.soc_esp8266_03', 'home') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}


      esp8266_03_motion:
        friendly_name: Wintergarten
        value_template: '{% if is_state("sensor.esp8266_03_pir", "ON") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("sensor.esp8266_03_pir", "ON") %}mdi:alert{% else %}mdi:eye-off{% endif %}'


      wintergarten_motion_last_triggered:
        friendly_name: "Wintergarten Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.sensor.esp8266_03_motion.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}
