################################################################
## Packages / NodeMCU #3
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:

    sensor.esp8266_03:
      entity_picture: /local/esp.jpg

    sensor.temperatur_esp8266_03:
      icon: mdi:thermometer
      friendly_name: Temperatur Wintergarten

    sensor.luftfeuchtigkeit_esp8266_03:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit Wintergarten

    sensor.esp8266_03_ip:
      icon: mdi:server-network
      friendly_name: IPv4 ESP 03

###############################################################################
#  Sensors
###############################################################################
binary_sensor:
  - platform: mqtt
    state_topic: "sensor_esp8266_03/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
    name: "sensor_esp8266_03_status_binary"

sensor:
  - platform: mqtt
    name: "ESP8266 03 Status"
    state_topic: "sensor_esp8266_03/status"
    payload_on: "online"
    payload_off: "offline"
    qos: 0

  - platform: mqtt
    name: "Temperatur ESP8266 03"
    state_topic: "sensor_esp8266_03/sensor/temperature/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Luftfeuchtigkeit ESP8266 03"
    state_topic: "sensor_esp8266_03/sensor/humidity/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "ESP8266 03 PIR"
    availability_topic: "sensor_esp8266_03/status"
    state_topic: "sensor_esp8266_03/binary_sensor/motion/state"
    qos: 0

  - platform: mqtt
    name: "ESP8266 03 Signal"
    state_topic: "sensor_esp8266_03/sensor/rssi/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "dB"


  - platform: mqtt
    name: "ESP8266 03 Uptime"
    state_topic: "sensor_esp8266_03/sensor/uptime/state"
    availability_topic: "sensor_esp8266_03/status"
    qos: 0
    unit_of_measurement: "seconds"

  - platform: template
    sensors:

      esp8266_03:
        friendly_name: 'ESP8266 #3'
        value_template: "{{ 'Online' if is_state('device_tracker.esp8266_03_ping', 'home') else 'Offline' }}"

      esp8266_03_status_var:
        friendly_name: "ESP8266 03 Status"
        value_template: >-
           {%- if is_state('device_tracker.esp8266_03_ping', 'home') -%}
             Online!  Uptime: {{ states.sensor.esp8266_03_uptime_human.state }}
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}
      esp8266_03_uptime_human:
        friendly_name: Uptime esp8266_03
        value_template: >-
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}

              {%- set weeks = seconds // intervals.weeks -%}
              {%- set seconds = seconds % intervals.weeks -%}
              {{- comma() ~ weeks ~ 'w' if weeks -}}

              {%- set days = seconds // intervals.days -%}
              {%- set seconds = seconds % intervals.days -%}
              {{- comma() ~ days ~ 'd' if days -}}

              {%- set hours = seconds // intervals.hours -%}
              {%- set seconds = seconds % intervals.hours -%}
              {{- comma() ~ hours ~ 'h' if hours -}}

              {%- set minutes = seconds // intervals.minutes -%}
              {{- comma() ~ minutes ~ 'm' if minutes -}}

              {%- set seconds = seconds % intervals.minutes -%}
              {{- comma() ~ seconds ~ 's' if seconds -}}
            {%- endmacro %}
            {{ human_time(states.sensor.esp8266_03_uptime.state | int   ) }}

      esp8266_03_motion:
        friendly_name: Wintergarten
        value_template: '{% if is_state("sensor.esp8266_03_pir", "ON") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("sensor.esp8266_03_pir", "ON") %}mdi:alert{% else %}mdi:eye-off{% endif %}'


      wintergarten_motion_last_triggered:
        friendly_name: "Wintergarten Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.sensor.esp8266_03_motion.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}
