#############################################################
## Packages / NodeMCU #7                                   ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config ##
#############################################################
homeassistant:
##############
#  Sensors  ##
##############
sensor:

  - platform: template
    sensors:


      esp8266_07_status_var:
        friendly_name: "ESP8266 07 Status"
        value_template: >-
           {%- if is_state('device_tracker.soc_esp8266_07', 'home') -%}
             Online!
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}
        icon_template: >-
          {% if is_state('device_tracker.soc_esp8266_07', 'home') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}
