################################################################
## Packages / NodeMCU #2
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:
    sensor.esp8266_02_temperature:
      icon: mdi:thermometer
      friendly_name: Temperatur ELW Regal

    sensor.esp8266_02_humidity:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit ELW Regal

    binary_sensor.esp8266_02_motion:
      friendly_name: ELW Regal


###############################################################################
#  Sensors
###############################################################################


sensor:

  - platform: template
    sensors:

      esp8266_02_status_var:
        friendly_name: "ESP8266 02 Status"
        value_template: >-
           {%- if is_state('binary_sensor.esp8266_02_status', 'on') -%}
             Online! Uptime: {{ states.sensor.esp8266_02_uptime_format.state }}
           {%- else -%}
             Node offline!
           {%- endif -%}
        icon_template: >-
          {% if is_state('binary_sensor.esp8266_02_status', 'on') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}

      esp8266_02_uptime_format:
        friendly_name: Uptime esp8266_02
        value_template: >-
           {% if states('binary_sensor.esp8266_02_status') | lower == "off" %}
             Node offline
           {% else %}
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}

              {%- set weeks = seconds // intervals.weeks -%}
              {%- set seconds = seconds % intervals.weeks -%}
              {{- comma() ~ weeks ~ 'w' if weeks -}}

              {%- set days = seconds // intervals.days -%}
              {%- set seconds = seconds % intervals.days -%}
              {{- comma() ~ days ~ 'd' if days -}}

              {%- set hours = seconds // intervals.hours -%}
              {%- set seconds = seconds % intervals.hours -%}
              {{- comma() ~ hours ~ 'h' if hours -}}

              {%- set minutes = seconds // intervals.minutes -%}
              {{- comma() ~ minutes ~ 'm' if minutes -}}

              {%- set seconds = seconds % intervals.minutes -%}
              {{- comma() ~ seconds ~ 's' if seconds -}}
            {%- endmacro %}
            {{ human_time(states.sensor.esp8266_02_uptime.state | int   ) }}
            {% endif %}


      esp8266_02_motion:
        friendly_name: ELW
        value_template: '{% if is_state("binary_sensor.esp8266_02_motion", "on") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("binary_sensor.esp8266_02_motion", "on") %}mdi:alert{% else %}mdi:eye-off{% endif %}'


      elw_motion_last_triggered:
        friendly_name: "ELW Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.sensor.esp8266_02_motion.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}
