################################################################
## Packages / NodeMCU #4
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:

    sensor.esp8266_04:
      entity_picture: /local/esp.jpg

    sensor.temperatur_esp8266_04:
      icon: mdi:thermometer
      friendly_name: Temperatur esp04

    sensor.luftfeuchtigkeit_esp8266_04:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit esp04

    switch.esp04_led_green:
      icon: mdi:led-outline
      friendly_name: Grüne LED

    switch.esp04_led_yellow:
      icon: mdi:led-outline
      friendly_name: Gelbe LED

    switch.esp04_led_red:
      icon: mdi:led-outline
      friendly_name: Rote LED

    sensor.esp8266_04_ip:
      icon: mdi:server-network
      friendly_name: IPv4 ESP 04

###############################################################################
#  Sensors
###############################################################################
sensor:

  - platform: mqtt
    name: "ESP8266 04 IP"
    state_topic: "sensor_esp8266_04/IP"
    availability_topic: "sensor_esp8266_04/status"
    payload_available: "Connected"
    payload_not_available: "Connection Lost"
    qos: 0





  - platform: mqtt
    name: "ESP8266 04 Status"
    state_topic: "sensor_esp8266_04/status"
    qos: 0

  - platform: mqtt
    name: "ESP8266 04 Uptime"
    state_topic: "sensor_esp8266_04/uptime/minutes"
    qos: 0
    unit_of_measurement: "minutes"

  - platform: mqtt
    name: "ESP8266 04 Signal"
    state_topic: "sensor_esp8266_04/signal/rssi"
    qos: 0
    unit_of_measurement: "dB"

  - platform: template
    sensors:


      esp8266_04_status_var:
        friendly_name: "ESP8266 04 Status"
        value_template: >-
           {%- if is_state('device_tracker.soc_esp8266_04', 'home') -%}
             Online! Uptime: {{ states.sensor.esp8266_04_uptime_human.state }}
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}
        icon_template: >-
          {% if is_state('device_tracker.soc_esp8266_04', 'home') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}
      esp8266_04_uptime_human:
        friendly_name: Uptime esp8266_04
        value_template: >-
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}

             {%- set weeks = seconds // intervals.weeks -%}
             {%- set seconds = seconds % intervals.weeks -%}
             {{- comma() ~ weeks ~ 'w' if weeks -}}

             {%- set days = seconds // intervals.days -%}
             {%- set seconds = seconds % intervals.days -%}
             {{- comma() ~ days ~ 'd' if days -}}

             {%- set hours = seconds // intervals.hours -%}
             {%- set seconds = seconds % intervals.hours -%}
             {{- comma() ~ hours ~ 'h' if hours -}}

             {%- set minutes = seconds // intervals.minutes -%}
             {{- comma() ~ minutes ~ 'm' if minutes -}}

             {%- set seconds = seconds % intervals.minutes -%}
             {{- comma() ~ seconds ~ 's' if seconds -}}
           {%- endmacro %}
           {{ human_time(states.sensor.esp8266_04_uptime.state | int * 60) }}



###############################################################################
#  switch
###############################################################################
switch:

  - platform: mqtt
    name: "esp04_led_red"
    state_topic: "sensor_esp8266_04/rot/Switch"
    command_topic: "sensor_esp8266_04/gpio/14"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "esp04_led_green"
    state_topic: "sensor_esp8266_04/gruen/Switch"
    command_topic: "sensor_esp8266_04/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "esp04_led_yellow"
    state_topic: "sensor_esp8266_04/gelb/Switch"
    command_topic: "sensor_esp8266_04/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
