alias: 'DeviceTracker Christoph home'
initial_state: True
condition:
  condition: state
  entity_id: input_boolean.chrishome
  state: 'off'
trigger:
  - platform: state
    entity_id: device_tracker.christoph_ip
    to: 'home'
  - platform: state
    entity_id: device_tracker.pixel_2_xl
    to: 'home'
  - platform: state
    entity_id: device_tracker.chop3_oneplus3
    to: 'home'
  - platform: state
    entity_id: sensor.tasker_chris
    to: 'home'
  - platform: state
    entity_id: switch.christoph_mqtt
    to: 'on'
action:
   service: homeassistant.turn_on
   entity_id: input_boolean.chrishome
