alias: "Stehlampe nach Sonnenuntergang anschalten"
initial_state: False
trigger:
  platform: sun
  event: sunset
  offset: "-00:20:00"
action:
  service: switch.turn_on
  entity_id: switch.wemoswitch2