alias: 1 OG Stehlampe bei erster Bewegung nach Sonnenuntergang anschalten
initial_state: False
trigger:
  platform: state
  entity_id: sensor.esp8266_01_pir
  from: '0'
  to: '1'
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
action:
  - service: switch.turn_on
    entity_id: switch.wemoswitch2
  - service: automation.turn_off
    entity_id: automation.1_og_stehlampe_bei_erster_bewegung_nach_sonnenuntergang_anschalten
  - service: notify.pushbullet
    data_template:
      message: >
         {{ states.sensor.date__time.state }} {{ trigger.to_state.attributes.friendly_name }} hat das erste Mal nach Sonnenuntergang ausgelöst und die Stehlampe wurde angeschaltet!
