alias: "Akkuladeautomatik"
initial_state: False
trigger:
  platform: numeric_state
  entity_id: sensor.fibaro_system_fgwpef_wall_plug_gen5_power_3_4
  below: 0.1
action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }} Das Ladegerät verbaucht keinen Strom mehr und die Steckdose wurde ausgeschaltet!'
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0
  - service: automation.turn_off
    entity_id: automation.akkuladeautomatik