alias: "HDD Alarm"
trigger:
  platform: numeric_state
  entity_id: sensor.disk_use_
  above: 25.0
action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }}: Der Speicherplatz geht zur Neige! /dev/root: {{ states.sensor.disk_use_.state }}%!'
  - service: notify.email
    data:
      title: 'HA: Speicherplatz'
      message: '{{ states.sensor.date__time.state }}: Der Speicherplatz geht zur Neige! /dev/root: {{ states.sensor.disk_use_.state }}%!'