alias: "sshd Alarm"
trigger:
  platform: state
  entity_id: sensor.process_sshd
  from: 'on'
  to: 'off'
action:
  - service: notify.pushbullet
    data:
      title: 'HomeAssistant: Process Monitor'
      message: '{{ states.sensor.date__time.state }}: Der SSH Daemon läuft nicht!'
  - service: notify.email
    data:
      title: 'HomeAssistant: Process Monitor'
      message: '{{ states.sensor.date__time.state }}: Der SSH Daemon läuft nicht!'