alias: 'Bewegungsmelder ELW Abwesenheit'
trigger:
  platform: mqtt
  topic: motion
  payload: 'on'
condition:
  condition: state
  entity_id: input_boolean.chrishome
  state: 'off'
action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }}: Bewegung in der ELW (RPI PIR)!'