alias: 'Bewegungsmelder ELW Abwesenheit Z-Wave'
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
  from: '0'
  to: '8'
condition:
  condition: state
  entity_id: input_boolean.chrishome
  state: 'off'
action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }}: Bewegung in der ELW (Z-Wave)!'