alias: Bewegungsmelder ELW Licht Z-Wave
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
  from: '0'
  to: '8'
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: state
    entity_id: device_tracker.oneplus3bt
    state: "home"
  - condition: state
    entity_id: switch.110113
    state: "off"
action:
  - service: switch.turn_on
    entity_id: switch.110113
  - delay: '{{ states.input_select.tuerlicht.state | int }}'
  - service: switch.turn_off
    entity_id: switch.110113