alias: Benachrichtigung Bewegungsmelder 1 OG -> motion.txt
trigger:
  - platform: state
    entity_id: sensor.esp8266_01_pir
    from: 'off'
    to: 'on'
action:
  - service: notify.motion
    data_template:
      message: >
         {{ states.sensor.date__time.state }} Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde aktiviert!