alias: Licht Slider move
trigger:
  platform: state
  entity_id: input_slider.tuerlicht_intervall
action:
  service: mqtt.publish
  data_template:
    topic: "setLicht"
    retain: true
    payload: '{{ states.input_slider.tuerlicht_intervall.state | int }}'
