alias: MQTT LED
trigger:
  platform: state
  entity_id: input_select.led_mqtt
action:
  service: mqtt.publish
  data_template:
    topic: "inTopic"
    retain: true
    payload: '{{ states.input_select.led_mqtt.state }}'
