# MQTT Topic setLicht payload ->> slider value
alias: Set Licht slider
trigger:
  platform: mqtt
  topic: "setLicht"

action:
   service: input_slider.select_value
   data_template:
    entity_id: input_slider.tuerlicht_intervall
    value: '{{ trigger.payload}}'