alias: "Benachrichtung boolean change home"
initial_state: False
trigger:
  platform: state
  entity_id: input_boolean.chrishome
  from: 'off'
  to: 'on'
action:
  service: notify.pushbullet
  data:
    message: 'HA Input boolean für chrishome ist jetzt on'