alias: "Benachrichtung boolean change not_home"
initial_state: False
trigger:
  platform: state
  entity_id: input_boolean.chrishome
  from: 'on'
  to: 'off'
action:
  service: notify.pushbullet
  data:
    message: 'HA Input boolean für chrishome ist jetzt OFF'