alias: zwave bewegungsmelder test 2
initial_state: False
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
  from: '8'
  to: '0'
action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.date__time.state }}testsensor z wave wurde resettet'