## Automations for own status
# Thanks 2 Ron Mar (http://ronmar.co/)

# Home status from monitor status
alias: "stat-christoph_Home status from monitor status"
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.sonoff1_use
    from: 'Ja'
    to: 'Nein'
#     for:
#       minutes: 3
condition:
  - condition: state
    entity_id: input_boolean.chrishome
    state: "on"


action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.christoph_status
      option: '{% if is_state("device_tracker.pixel_2_xl", "home") %}In der ELW{% else %}Anwesend{% endif %}'
