## Automations for own status
# Thanks 2 Ron Mar (http://ronmar.co/)

# Home status from bluetooth status
alias: "stat-christoph_Home status from bluetooth status"
initial_state: True
trigger:
  - platform: state
    entity_id: device_tracker.pixel_2_xl
    from: 'not_home'
    to: 'home'

action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.christoph_status
      option: '{% if is_state("sensor.sonfoff1_use", "Ja") %}Am PC{% else %}In der ELW{% endif %}'