alias: 'Trafficrequest via web hrw'
initial_state: True
trigger:
  platform: mqtt
  topic: traffic_status
  payload: 'hrw'
action:
  - service: notify.pushbullet
    data:
      title: "Sie haben Verkehrsdaten requestiert! ({{ now().strftime('%d.%m.%Y %H:%M:%S') }})"
      message: >
         Hallo,
         
         Laut Google beträgt die aktuelle Fahrzeit
         
         von Daheim zur HRW: {{ states.sensor.zuhause__hauptrettungswache.state }} Minuten
         
         und von der HRW nach Hause: {{ states.sensor.hauptrettungswache__zuhause.state }} Minuten.
         
         Hade, Tschuss!
