alias: 'Trafficrequest'
initial_state: off
trigger:
  platform: mqtt
  topic: traffic_status
  payload: 'frank'
action:
  - service: notify.mail2frank
    data:
      title: "Sie haben Verkehrsdaten requestiert!"
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }}
         
         Hallo,
         
         Laut Google beträgt die aktuelle Fahrzeit
         
         von Daheim zur Arbeit: {{ states.sensor.frank__abtis.state }} Minuten
         
         und von der Arbeit nach Hause: {{ states.sensor.abtis__frank.state }} Minuten.
         
         Hade, Tschuss!
