alias: 'Trafficrequest petros'
initial_state: off
trigger:
  platform: mqtt
  topic: traffic_status
  payload: 'petros'
action:
  - service: notify.mail2petros
    data:
      title: "Sie haben Verkehrsdaten requestiert!"
      message: >
         {{ now().strftime('%d.%m.%Y %H:%M:%S') }}
         
         Hallo,
         
         Laut Google beträgt die aktuelle Fahrzeit
         
         von Daheim zur Arbeit: {{ states.sensor.petros__ils.state }} Minuten
         
         und von der Arbeit nach Hause: {{ states.sensor.ils__petros.state }} Minuten.
         
         Hade, Tschuss!
