##############################################################
### Packages / 433MHz Plugs                                ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:
  customize:
    switch.11011_A:
      friendly_name: Bettlicht
      icon: mdi:lamp
      persistent: true
    switch.11011_B:
      friendly_name: Schreibtischlicht
      icon: mdi:spotlight-beam
      persistent: true
    switch.11011_C:
      friendly_name: Türlicht
      icon: mdi:spotlight
      persistent: true
    switch.11001_A:
      friendly_name: ESP Schreibtisch
      icon: mdi:power-plug
      persistent: true
    switch.11001_B:
      friendly_name: RPi IR Cam
      icon: mdi:raspberrypi
      persistent: true
    switch.11001_C:
      friendly_name: IR Strahler
      icon: mdi:spotlight
      persistent: true

switch:
  - platform: mqtt
    name: "11011_A"
    command_topic: "home/commands/MQTTto433"
    payload_on: "263505"
    payload_off: "263508"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "11011_B"
    command_topic: "home/commands/MQTTto433"
    payload_on: "266577"
    payload_off: "266580"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "11011_C"
    command_topic: "home/commands/MQTTto433"
    payload_on: "267345"
    payload_off: "267348"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "11001_A"
    command_topic: "home/commands/MQTTto433"
    payload_on: "329041"
    payload_off: "329044"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "11001_B"
    command_topic: "home/commands/MQTTto433"
    payload_on: "332113"
    payload_off: "332116"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "11001_C"
    command_topic: "home/commands/MQTTto433"
    payload_on: "332881"
    payload_off: "332884"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
