##############################################################
### Packages / 433MHz Plugs                                ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:
  customize:
    switch.110111:
      friendly_name: Bettlicht
      icon: mdi:lamp
      persistent: true
    switch.110112:
      friendly_name: Schreibtischlicht
      icon: mdi:spotlight-beam
      persistent: true
    switch.110113:
      friendly_name: Türlicht
      icon: mdi:spotlight
      persistent: true
    switch.110011:
      friendly_name: ESP Schreibtisch
      icon: mdi:power-plug
      persistent: true
    switch.110012:
      friendly_name: RPi IR Cam
      icon: mdi:raspberrypi
      persistent: true
    switch.110013:
      friendly_name: IR Strahler
      icon: mdi:spotlight
      persistent: true

### send used from https://github.com/xkonni/raspberry-remote to control 433MHz outlets

switch:
  platform: command_line
  switches:
    11011_1:
      command_on: /home/homeassistant/send 11011 1 1
      command_off: /home/homeassistant/send 11011 1 0
  
    11011_2:
      command_on: /home/homeassistant/send 11011 2 1
      command_off: /home/homeassistant/send 11011 2 0
  
    11011_3:
      command_on: /home/homeassistant/send 11011 3 1
      command_off: /home/homeassistant/send 11011 3 0
  
    11001_1:
      command_on: /home/homeassistant/send 11001 1 1
      command_off: /home/homeassistant/send 11001 1 0
  
    11001_2:
      command_on: /home/homeassistant/send 11001 2 1
      command_off: /home/homeassistant/send 11001 2 0
  
    11001_3:
      command_on: /home/homeassistant/send 11001 3 1
      command_off: /home/homeassistant/send 11001 3 0
  