########################################################################
## Packages / Alarms                                                  ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:






#################
### automation ##
#################

automation:

#notification about all sensors when not home
### Thanks 2 @brahmafear (initial version)
  - alias: Benachrichtigung aller Bewegunsgmelder in der ELW
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.aeotec_zw100_multisensor_6_burglar
        from: '0'
        to: '8'
      - platform: state
        entity_id: binary_sensor.esp8266_02_pir
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.esp32_01_door_state
        from: 'off'
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.chrishome'
          state: 'off'
        - condition: template
          value_template: >
            {% if states.automation.benachrichtigung_aller_bewegunsgmelder_in_der_elw.last_triggered is not none %}
              {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.benachrichtigung_aller_bewegunsgmelder_in_der_elw.attributes.last_triggered) | int > 60 %} true {% else %} false
              {% endif %}
            {% else %}
            false
            {% endif %}
    action:
      - service: notify.telegram_christoph
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }}
             Obacht: {{ trigger.to_state.attributes.friendly_name }} wurde aktiviert!

#door open when leaving
  - alias: leave_door_open_elw
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.esp32_01_door_state'
          state: 'on'

    action:
      - service: notify.telegram_christoph
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }}
             Obacht: Die Türe ELW ist noch offen!
#Computer in use when not home
  - alias: computer_in_use_when_not_home
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff2_use
        to: 'Ja'
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.chrishome'
          state: 'off'

    action:
      - service: notify.telegram_christoph
        data_template:
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }}
             Obacht: Der Comnputer wurde angeschaltet

