##############################################################
### Packages / Certification Renewal                       ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:
  customize:
    sensor.nullx_cert_expiry:
      friendly_name: SSL Cert. 0x711
      icon: mdi:lock
    sensor.cvoid_cert_expiry:
      friendly_name: SSL Cert. cvoid
      icon: mdi:lock
group:
  ssl_cert:
    name: "SSL Cert. Status"
    control: hidden
    entities:
      - sensor.nullx_cert_expiry
      - sensor.cvoid_cert_expiry


sensor:
  - platform: cert_expiry
    host: 0x711.de
    name: nullx_cert_expiry

  - platform: cert_expiry
    host: cvoid.de
    name: cvoid_cert_expiry


automation:
  - alias: "0x_cert_expiry_alarm"
    initial_state: True
    trigger:
      platform: template
      value_template: '{{ states.sensor.nullx_cert_expiry.state|float < 14}}'
    condition:
      - condition: template
        value_template: "{{ states('sensor.nullx_cert_expiry') != 'unknown' }}"
    action:
      - service: notify.pushbullet
        data:
          title: 'HomeAssistant: 0x711.de SSL Certification'
          message: '{{ states.sensor.date_time.state }}: Das SSL Zertifikat für 0x711.de läuft in weniger als {{ states.sensor.nullx_cert_expiry.state}} Tagen ab!'
      - service: notify.email
        data:
          title: 'HomeAssistant: 0x711.de SSL Certification'
          message:  '{{ states.sensor.date_time.state }}: Das SSL Zertifikat für 0x711.de läuft in weniger als {{ states.sensor.nullx_cert_expiry.state}} Tagen ab!'

  - alias: "cvoid_cert_expiry_alarm"
    initial_state: True
    trigger:
      platform: template
      value_template: '{{ states.sensor.cvoid_cert_expiry.state|float < 14}}'
    condition:
      - condition: template
        value_template: "{{ states('sensor.cvoid_cert_expiry') != 'unknown' }}"
    action:
      - service: notify.pushbullet
        data:
          title: 'HomeAssistant: cvoid.de SSL Certification'
          message: '{{ states.sensor.date_time.state }}: Das SSL Zertifikat für cvoid.de läuft in weniger als {{ states.sensor.cvoid_cert_expiry.state}} Tagen ab!'
      - service: notify.email
        data:
          title: 'HomeAssistant: cvoid.de SSL Certification'
          message: '{{ states.sensor.date_time.state }}: Das SSL Zertifikat für cvoid.de läuft in weniger als {{ states.sensor.cvoid_cert_expiry.state}} Tagen ab!'
