##############################################################
### Packages / custom avg sensor                           ###
### https://github.com/Limych/ha-average                   ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################
homeassistant:
sensor:


# --> sensor name --> inclues/recorder.yaml
#outside temp
  - platform: average
    name: 'avg_temp_outside_esp_1day'
    duration:
      days: 1
    entities:
      - sensor.esp32_02_temperature
      - sensor.esp32_03_temperature


  - platform: average
    name: 'avg_temp_outside_esp_3day'
    duration:
      days: 3
    entities:
      - sensor.esp32_02_temperature
      - sensor.esp32_03_temperature

  - platform: average
    name: 'avg_temp_outside_esp_7day'
    duration:
      days: 7
    entities:
      - sensor.esp32_02_temperature
      - sensor.esp32_03_temperature

#inside temp
  - platform: average
    name: 'avg_temp_inside_elw_1day'
    duration:
      days: 1
    entities:
      - sensor.temperatur_esp8266_02
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.esp8266_06_temperature
  - platform: average
    name: 'avg_temp_inside_elw_3day'
    duration:
      days: 3
    entities:
      - sensor.temperatur_esp8266_02
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.esp8266_06_temperature
  - platform: average
    name: 'avg_temp_inside_elw_7day'
    duration:
      days: 7
    entities:
      - sensor.temperatur_esp8266_02
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.esp8266_06_temperature


#free drive space

  - platform: average
    name: 'avg_free_space_qnap_1y'
    duration:
      days: 365
    entities:
      - sensor.qnap1_free_space_datavol1_gib
