##############################################################
### Packages / Device Tracker and Home Status              ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks 2 Ron Mar                                       ###
##############################################################

homeassistant:
  customize:
    automation.DeviceTracker_Christoph_not_home:
      friendly_name: 'Christoph geht '
    automation.DeviceTracker_Christoph_home:
      friendly_name: 'Christoph kommt'
    automation.select_christoph_Home_status_from_input_boolean:
      friendly_name: 'setze status auf anwesend'
    automation.select_christoph_Home_status_from_bluetooth_status:
      friendly_name: 'setze status auf in der elw oder am pc'
    automation.select_christoph_away_status_from_input_boolean:
      friendly_name: 'setze status auf abwesend'
    automation.select_christoph_home_status_from_monitor_status:
      friendly_name: 'setzte status am pc'
    automation.select_christoph_home_status_away_monitor_status:
      friendly_name: 'setze status auf anwesend oder in der elw'
    automation.select_christoph_home_status_away_elw:
      friendly_name: 'setze status auf anwesend von der in der elw'

### template sensors last changed 

sensor:
  - platform: template
    sensors:
      device_tracker_traude_last_changed:
        friendly_name: "Traude letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.device_tracker.traude_ip.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_ewald_last_changed:
        friendly_name: "Ewald letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.device_tracker.ewald_ip.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_christoph_last_changed:
        friendly_name: "Christoph letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.input_boolean.chrishome.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_christoph_verbose:
        friendly_name: "Christoph State Update"
        value_template: >-
          {{ states.sensor.tasker_home.state }} via {{ states.sensor.tasker_home_connection.state }}
###### STATE CARD for views.yaml

group:
  device_tracker:
    control: hidden
    icon: mdi:crosshairs-gps
    name: DeviceTracker
    entities:
      - automation.DeviceTracker_Christoph_not_home
      - automation.DeviceTracker_Christoph_home
      - automation.select_christoph_Home_status_from_input_boolean
      - automation.select_christoph_Home_status_from_bluetooth_status
      - automation.select_christoph_away_status_from_input_boolean
      - automation.select_christoph_home_status_from_monitor_status
      - automation.select_christoph_home_status_away_monitor_status
      - automation.select_christoph_home_status_away_elw
      - automation.select_christoph_home_status_home_oben


input_boolean:
  chrishome:
    name: "Christoph"
    initial: on
    icon: mdi:cellphone-iphone

input_select:
  christoph_status:
    name: Status Christoph
    initial: 'kA'
    options:
      - 'kA'
      - 'Nicht am PC'
      - 'Am PC'
      - 'In der ELW'
      - 'Oben'
      - 'Anwesend'
      - 'Abwesend'

automation:

#Switch input_boolean from on to off when gone

  - alias: 'DeviceTracker_Christoph_not_home'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrishome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.christoph_ip
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: sensor.tasker_home
        to: 'not_home'
        for:
          minutes: 5
    
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.chrishome
    
      # - service: notify.pushbullet
        # data_template:
          # message: >
             # {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Trigger: {{ trigger.to_state.attributes.friendly_name }} HomeSwitch now: {{ states.input_boolean.chrishome.state }}!

#switch input_boolean from off to on 

  - alias: 'DeviceTracker_Christoph_home'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrishome
      state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.christoph_ip
        to: 'home'
      - platform: state
        entity_id: device_tracker.chris_bluetooth_nuc
        to: 'home'
      - platform: state
        entity_id: device_tracker.chris_bluetooth_rpi3
        to: 'home'
      - platform: state
        entity_id: sensor.tasker_home
        to: 'home'
    action:
       service: homeassistant.turn_on
       entity_id: input_boolean.chrishome


# input select for home 

  - alias: "select_christoph_Home_status_from_input_boolean"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        from: 'off'
        to: 'on'
    
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Anwesend"

# input select for home or ELW

  - alias: "select_christoph_Home_status_from_bluetooth_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: device_tracker.chris_bluetooth_nuc
        from: 'not_home'
        to: 'home'
    
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.christoph_status
          option: '{% if is_state("sensor.sonoff1_use", "Ja") %}Am PC{% else %}In der ELW{% endif %}'

#input select for away

  - alias: "select_christoph_away_status_from_input_boolean"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        from: 'on'
        to: 'off'
    
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Abwesend"

#input select at pc

  - alias: "select_christoph_home_status_from_monitor_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff1_use
        from: 'Nein'
        to: 'Ja'
    #     for:
    #       minutes: 1
    
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Am PC"

#input select not at pc

  - alias: "select_christoph_home_status_away_monitor_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff1_use
        from: 'Ja'
        to: 'Nein'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"
    
    
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.christoph_status
          option: '{% if is_state("device_tracker.chris_bluetooth_nuc", "home") %}In der ELW{% else %}Anwesend{% endif %}'


#input select not in the elw

  - alias: "select_christoph_home_status_away_elw"
    initial_state: True
    trigger:
      - platform: state
        entity_id: device_tracker.chris_bluetooth_nuc
        from: 'home'
        to: 'not_home'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"
    
    
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Anwesend"



#input select upstairs



  - alias: "select_christoph_home_status_home_oben"
    initial_state: True
    trigger:
      - platform: state
        entity_id: device_tracker.chris_bluetooth_rpi3
        from: 'not_home'
        to: 'home'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"
    
    
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Oben"