##############################################################
### Packages / Device Tracker and Home Status              ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks 2 Ron Mar                                       ###
##############################################################

homeassistant:
  customize:
    automation.DeviceTracker_Christoph_not_home:
      friendly_name: 'Christoph geht '
    automation.DeviceTracker_Christoph_home:
      friendly_name: 'Christoph kommt'
    automation.select_christoph_Home_status_from_input_boolean:
      friendly_name: 'setze status auf anwesend'
    automation.select_christoph_Home_status_from_bluetooth_status:
      friendly_name: 'setze status auf in der elw oder am pc'
    automation.select_christoph_away_status_from_input_boolean:
      friendly_name: 'setze status auf abwesend'
    automation.select_christoph_home_status_from_monitor_status:
      friendly_name: 'setzte status am pc'
    automation.select_christoph_home_status_away_monitor_status:
      friendly_name: 'setze status auf anwesend oder in der elw'
    automation.select_christoph_home_status_away_elw:
      friendly_name: 'setze status auf anwesend von der in der elw'

### template sensors last changed

sensor:
  - platform: template
    sensors:
      device_tracker_traude_last_changed:
        friendly_name: "Traude letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.device_tracker.user_devices_phone_traude.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_ewald_last_changed:
        friendly_name: "Ewald letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.device_tracker.user_devices_phone_ewald.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_christoph_last_changed:
        friendly_name: "Christoph letzte Änderung"
        value_template: >-
          {{ as_timestamp(states.input_boolean.chrishome.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}

  - platform: template
    sensors:
      device_tracker_christoph_verbose:
        friendly_name: "Christoph State Update"
        value_template: >-
          {{ states.sensor.tasker_home.state }} via {{ states.sensor.tasker_home_connection.state }}

#bt state from rpi zero/nuc https://github.com/andrewjfreyer/presence

  - platform: mqtt
    state_topic: 'location/elw/B4:F1:DA:2C:91:4E'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'monitor_pixel2_elw'

  - platform: mqtt
    state_topic: 'location/elw/3C:28:6D:08:DD:DA'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'monitor_pixel3_elw'

  - platform: mqtt
    state_topic: 'location/elw/F0:5C:77:F1:28:21'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'monitor_pixel4_elw'
  # - platform: mqtt
  #   state_topic: 'location/1og/B4:F1:DA:2C:91:4E'
  #   value_template: '{{ value_json.confidence }}'
  #   unit_of_measurement: '%'
  #   name: 'monitor_pixel2_1og'
  #
  # - platform: mqtt
  #   state_topic: 'location/1og/3C:28:6D:08:DD:DA'
  #   value_template: '{{ value_json.confidence }}'
  #   unit_of_measurement: '%'
  #   name: 'monitor_pixel3_1og'
###### STATE CARD for views.yaml

group:
  device_tracker:
    control: hidden
    icon: mdi:crosshairs-gps
    name: DeviceTracker
    entities:
      - automation.DeviceTracker_Christoph_not_home
      - automation.DeviceTracker_Christoph_home
      - automation.select_christoph_Home_status_from_input_boolean
      - automation.select_christoph_Home_status_from_bluetooth_status
      - automation.select_christoph_away_status_from_input_boolean
      - automation.select_christoph_home_status_from_monitor_status
      - automation.select_christoph_home_status_away_monitor_status
      - automation.select_christoph_home_status_away_elw
      - automation.select_christoph_home_status_home_oben
  familiegrp:
    name: Familie
    view: no
    icon: mdi:account-multiple
    entities:
      - input_boolean.chrishome
      - device_tracker.user_devices_phone_ewald
      - device_tracker.user_devices_phone_traude


  familiegrpstate:
    name: Letzte Änderung
    view: no
    icon: mdi:account-multiple
    entities:
      - sensor.device_tracker_christoph_last_changed
      - sensor.device_tracker_christoph_verbose
      - sensor.device_tracker_ewald_last_changed
      - sensor.device_tracker_traude_last_changed

input_boolean:
  chrishome:
    name: "Christoph Status"
    initial: off
    icon: mdi:cellphone-android

  chrisbluetooth:
    name: "Christoph Bluetooth Status ELW"
    initial: off
    icon:  mdi:bluetooth-audio

  # chrisbluetooth_1og:
  #   name: "Christoph Bluetooth Status 1OG"
  #   initial: off
  #   icon:  mdi:bluetooth-audio


input_select:
  christoph_status:
    name: Status Christoph
    initial: 'kA'
    options:
      - 'kA'
      - 'Nicht am PC'
      - 'Am PC'
      - 'In der ELW'
      - 'Oben'
      - 'Anwesend'
      - 'Abwesend'

automation:

#switch input_boolean bluetooth from on to off
  - alias: 'input_boolean_chrisbluetooth_off'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrisbluetooth
      state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.monitor_pixel4_elw
        below: 25
        # for:
        #   minutes: 2
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.chrisbluetooth
#switch input_boolean bluetooth from off to on
  - alias: 'input_boolean_chrisbluetooth_on'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrisbluetooth
      state: 'off'
    trigger:
      - platform: numeric_state
        entity_id: sensor.monitor_pixel4_elw
        above: 30
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.chrisbluetooth
#switch input_boolean bluetooth from on to off
  - alias: 'input_boolean_chrisbluetooth_1og_off'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrisbluetooth_1og
      state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.monitor_pixel3_1og
        below: 25
        # for:
        #   minutes: 2
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.chrisbluetooth_1og
#switch input_boolean_1og bluetooth from off to on
  - alias: 'input_boolean_chrisbluetooth_1og_on'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrisbluetooth_1og
      state: 'off'
    trigger:
      - platform: numeric_state
        entity_id: sensor.monitor_pixel3_1og
        above: 30
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.chrisbluetooth_1og
#Switch input_boolean homestate  from on to off when gone

  - alias: 'DeviceTracker_Christoph_not_home'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrishome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.user_devices_phone_christoph
        to: 'not_home'
        for:
          minutes: 5
      # - platform: state
      #   entity_id: sensor.tasker_home
      #   to: 'not_home'
      #   for:
      #     minutes: 5
      - platform: state
        entity_id: device_tracker.p4xl
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.chrishome

      # - service: notify.pushbullet
      #   data_template:
      #     message: >
      #        {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Trigger: {{ trigger.to_state.attributes.friendly_name }} HomeSwitch now: {{ states.input_boolean.chrishome.state }}!
      - service: notify.mobile_app_pixel_4_xl
        data_template:
          title: HomeSwitch OFF
          message: >
             {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Trigger: {{ trigger.to_state.attributes.friendly_name }} HomeSwitch now: {{ states.input_boolean.chrishome.state }}!

#switch input_boolean from off to on

  - alias: 'DeviceTracker_Christoph_home'
    initial_state: True
    condition:
      condition: state
      entity_id: input_boolean.chrishome
      state: 'off'
    trigger:
#nmap/unifi
      - platform: state
        entity_id: device_tracker.user_devices_phone_christoph
        to: 'home'
#gpslogger
      - platform: state
        entity_id: device_tracker.p4xl
        to: 'home'
      # - platform: state
      #   entity_id: device_tracker.chris_bluetooth_nuc
      #   to: 'home'
      # - platform: state
      #   entity_id: device_tracker.chris_bluetooth_rpi3
      #   to: 'home'
      # - platform: state
      #   entity_id: sensor.tasker_home
      #   to: 'home'
      - platform: state
        entity_id: input_boolean.chrisbluetooth
        to: 'on'
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.chrishome

    # - service: telegram_bot.send_message
    #   data_template:
    #     target: !secret telegram_chat_id_christoph
    #     message: >
    #       home state triggered by {{ trigger.to_state.attributes.friendly_name }}

    - service: notify.mobile_app_pixel_4_xl
      data_template:
        title: Welcome Home!
        message: >
           {{ now().strftime('%d.%m.%Y %H:%M:%S') }} home state triggered by {{ trigger.to_state.attributes.friendly_name }}
# input select for home

  - alias: "select_christoph_Home_status_from_input_boolean"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        from: 'off'
        to: 'on'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Anwesend"

# input select for home or ELW

  - alias: "select_christoph_Home_status_from_bluetooth_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrisbluetooth
        from: 'off'
        to: 'on'

    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.christoph_status
          option: '{% if is_state("sensor.sonoff1_use", "Ja") %}Am PC{% else %}In der ELW{% endif %}'

#input select for away

  - alias: "select_christoph_away_status_from_input_boolean"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        from: 'on'
        to: 'off'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Abwesend"

#input select at pc

  - alias: "select_christoph_home_status_from_monitor_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff1_use
        from: 'Nein'
        to: 'Ja'
    #     for:
    #       minutes: 1

    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Am PC"

#input select not at pc

  - alias: "select_christoph_home_status_away_monitor_status"
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff1_use
        from: 'Ja'
        to: 'Nein'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"


    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.christoph_status
          option: '{% if is_state("input_boolean.chrishome", "on") %}In der ELW{% else %}Anwesend{% endif %}'


#input select not in the elw

  - alias: "select_christoph_home_status_away_elw"
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.chrisbluetooth
        from: 'on'
        to: 'off'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"


    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Anwesend"



#input select upstairs



  - alias: "select_christoph_home_status_home_oben"
    initial_state: True
    trigger:
      - platform: state
        entity_id: device_tracker.chris_bluetooth_rpi3
        from: 'not_home'
        to: 'home'
    #     for:
    #       minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.chrishome
        state: "on"


    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.christoph_status
          option: "Oben"
# notification home states
  - alias: notify_homestate
    initial_state: false
    trigger:
      - platform: state
        entity_id:
          - device_tracker.user_devices_phone_traude
          - device_tracker.user_devices_phone_ewald
        from: 'not_home'
        to: 'home'

      - platform: state
        entity_id:
          - device_tracker.user_devices_phone_traude
          - device_tracker.user_devices_phone_ewald
        from: 'home'
        to: 'not_home'

      - platform: state
        entity_id:
          - input_boolean.chrishome
        from: 'off'
        to: 'on'

      - platform: state
        entity_id:
          - input_boolean.chrishome
        from: 'on'
        to: 'off'

    action:
      - service: notify.telegram_christoph
        data_template:
          message: >
            {% if (trigger.to_state.state  == "not_home" ) or (trigger.to_state.state == "off") %}
                {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist gegangen ({{ now().strftime('%d.%m.%Y %H:%M:%S') }})!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist daheim ({{ now().strftime('%d.%m.%Y %H:%M:%S') }})!
            {% endif %}

      - condition: state
        entity_id: input_boolean.chrisbluetooth
        state: 'on'

      # - service: notify.echodot
      #   data_template:
      #     message: >
      #       {% if (trigger.to_state.state  == "not_home" ) or (trigger.to_state.state == "off") %}
      #           {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist gegangen!
      #       {% else %}
      #         {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist daheim!
      #       {% endif %}

      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target: media_player.christophs_echo_dot
          message: >
            {% if (trigger.to_state.state  == "not_home" ) or (trigger.to_state.state == "off") %}
                {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist gegangen!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name|replace ('Christoph Status','Christoph') }} ist daheim!
            {% endif %}
