########################################################################
## Packages / ELW                                                     ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:

####################################
### automation lights auto on/off ##
####################################
#welcome home Automation
automation:
  - alias: turn_on_lights_when_coming_home
    initial_state: off
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        to: 'on'
    action:
      - wait_template: "{{ states.binary_sensor.esp32_01_door_state.state == 'on' }}"
      - service: automation.turn_off
        entity_id: automation.turn_on_lights_when_coming_home
      - delay: '00:00:20'
      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target: media_player.christophs_echo_dot
          message: >
             {% set person = 'Christoph' %}
             {% if now().strftime("%H")|int < 12 %}
             Guten Morgen
             {% elif now().strftime("%H")|int < 18 %}
             Guten Mittag
             {% else %}
             Guten Abend
             {% endif %}
             {{ [
             "schön dass du da bist " + person,
             "Sei gegrüßt " + person,
             "und willkommen zu hause " + person
             ] |random }}

      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states.sun.sun.state == 'below_horizon' }}"
      - service: scene.turn_on
        entity_id: scene.elw_relax
      - service: scene.turn_on
        entity_id: scene.flur_relax
      - delay: '{{ states.input_select.tuerlicht.state | int }}'
      - service: scene.turn_on
        entity_id: scene.flur_aus


#enable automation when leaving
  - alias: enable_automation_coming_home
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.chrishome
        to: 'off'
        for:
          minutes: 1
    action:
      - service: automation.turn_on
        entity_id: automation.turn_on_lights_when_coming_home


#disable lights when leaving
  - alias: 'ELW Licht ausschalten wenn BT nicht gefunden'
    initial_state: True
    trigger:
        - platform: state
          entity_id: input_boolean.chrisbluetooth
          to: 'off'
          for:
            minutes: 2
    action:
      - service: scene.turn_on
        entity_id: scene.elw_aus
