################################################################
## Packages / NodeMCU #4
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:

    sensor.esp8266_04:
      entity_picture: /local/esp.jpg

    sensor.temperatur_esp8266_04:
      icon: mdi:thermometer
      friendly_name: Temperatur esp04

    sensor.luftfeuchtigkeit_esp8266_04:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit esp04

    switch.grne_led:
      icon: mdi:led-outline
      friendly_name: Grüne LED

    switch.gelbe_led:
      icon: mdi:led-outline
      friendly_name: Gelbe LED

    switch.rote_led:
      icon: mdi:led-outline
      friendly_name: Rote LED

    sensor.esp8266_04_ip:
      icon: mdi:server-network
      friendly_name: IPv4 ESP 04

###############################################################################
#  Sensors
###############################################################################
sensor:

  - platform: mqtt
    name: "Temperatur ESP8266 04"
    state_topic: "sensor_esp8266_04/dht22/Temperature"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "ESP8266 04 IP"
    state_topic: "sensor_esp8266_04/IP"
    availability_topic: "sensor_esp8266_04/status"
    payload_available: "Connected"
    payload_not_available: "Connection Lost"
    qos: 0

  - platform: mqtt
    name: "Luftfeuchtigkeit ESP8266 04"
    state_topic: "sensor_esp8266_04/dht22/Humidity"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "ESP8266 04 PIR"
    state_topic: "sensor_esp8266_04/pir/motion"
    qos: 0

  - platform: mqtt
    name: "ESP8266 04 Status"
    state_topic: "sensor_esp8266_04/status"
    qos: 0

  - platform: mqtt
    name: "ESP8266 04 Uptime"
    state_topic: "sensor_esp8266_04/uptime/minutes"
    qos: 0
    unit_of_measurement: "minutes"

  - platform: mqtt
    name: "ESP8266 04 Signal"
    state_topic: "sensor_esp8266_04/signal/rssi"
    qos: 0
    unit_of_measurement: "dB"

  - platform: template
    sensors:

      esp8266_04:
        friendly_name: 'ESP8266 #4'
        value_template: "{{ 'Online' if is_state('device_tracker.esp8266_04_ping', 'home') else 'Offline' }}"

      esp8266_04_status_var:
        friendly_name: "ESP8266 04 Status"
        value_template: >-
           {%- if is_state('device_tracker.esp8266_04_ping', 'home') -%}
             Online! Uptime: {{ states.sensor.esp8266_04_uptime_human.state }}
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}

      esp8266_04_uptime_human:
        friendly_name: Uptime esp8266_04
        value_template: >-
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}
           
             {%- set weeks = seconds // intervals.weeks -%}
             {%- set seconds = seconds % intervals.weeks -%}
             {{- comma() ~ weeks ~ ' week' ~ ('s' if weeks != 1) if weeks -}}
           
             {%- set days = seconds // intervals.days -%}
             {%- set seconds = seconds % intervals.days -%}
             {{- comma() ~ days ~ ' day' ~ ('s' if days != 1) if days -}}
           
             {%- set hours = seconds // intervals.hours -%}
             {%- set seconds = seconds % intervals.hours -%}
             {{- comma() ~ hours ~ ' hour' ~ ('s' if hours != 1) if hours -}}
           
             {%- set minutes = seconds // intervals.minutes -%}
             {{- comma() ~ minutes ~ ' minute' ~ ('s' if minutes != 1) if minutes -}}
           
             {%- set seconds = seconds % intervals.minutes -%}
             {{- comma() ~ seconds ~ ' second' ~ ('s' if seconds != 1) if seconds -}}
           {%- endmacro %}
           {{ human_time(states.sensor.esp8266_04_uptime.state | int * 60) }}

      esp8266_04_motion:
        friendly_name: esp04
        value_template: '{% if is_state("sensor.esp8266_04_pir", "1") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("sensor.esp8266_04_pir", "1") %}mdi:alert{% else %}mdi:eye-off{% endif %}'


      esp04_motion_last_triggered:
        friendly_name: "esp04 Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.sensor.esp8266_04_motion.last_changed)|timestamp_custom('%H:%M:%S %d.%m.%Y') }}

###############################################################################
#  switch
###############################################################################
switch:

  - platform: mqtt
    name: "Rote LED"
    state_topic: "sensor_esp8266_04/rot/Switch"
    command_topic: "sensor_esp8266_04/gpio/14"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "Gr?ne LED"
    state_topic: "sensor_esp8266_04/gruen/Switch"
    command_topic: "sensor_esp8266_04/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "Gelbe LED"
    state_topic: "sensor_esp8266_04/gelb/Switch"
    command_topic: "sensor_esp8266_04/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
