################################################################
## Packages / NodeMCU #7
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config
################################################################
homeassistant:
  customize:

    sensor.esp8266_07:
      entity_picture: /local/esp.jpg

    sensor.temperatur_esp8266_07:
      icon: mdi:thermometer
      friendly_name: Temperatur Bad

    sensor.luftfeuchtigkeit_esp8266_07:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit Bad


###############################################################################
#  Sensors
###############################################################################
sensor:

  - platform: mqtt
    name: "Temperatur ESP8266 07"
    state_topic: "sensor_esp8266_07/dht22/Temperature"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Luftfeuchtigkeit ESP8266 07"
    state_topic: "sensor_esp8266_07/dht22/Humidity"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "ESP8266 07 PIR"
    state_topic: "sensor_esp8266_07/pir/motion"
    qos: 0

  - platform: mqtt
    name: "ESP8266 07 Radar"
    state_topic: "sensor_esp8266_07/radar/motion"
    qos: 0
  - platform: mqtt
    name: "ESP8266 07 IP"
    state_topic: "sensor_esp8266_07/status_ip"
    qos: 0

  - platform: mqtt
    name: "ESP8266 07 Status"
    state_topic: "sensor_esp8266_07/status"
    qos: 0

  - platform: mqtt
    name: "ESP8266 07 Uptime"
    state_topic: "sensor_esp8266_07/uptime/minutes"
    qos: 0
    unit_of_measurement: "minutes"

  - platform: mqtt
    name: "ESP8266 07 Signal"
    state_topic: "sensor_esp8266_07/signal/rssi"
    qos: 0
    unit_of_measurement: "dB"

  - platform: template
    sensors:

      esp8266_07:
        friendly_name: 'ESP8266 #7'
        value_template: "{{ 'Online' if is_state('device_tracker.esp8266_07_ping', 'home') else 'Offline' }}"

      esp8266_07_status_var:
        friendly_name: "ESP8266 07 Status"
        value_template: >-
           {%- if is_state('device_tracker.esp8266_07_ping', 'home') -%}
             Online! Uptime: {{ states.sensor.esp8266_07_uptime_human.state }}
           {%- else -%}
             Sensor ist offline!
           {%- endif -%}

      esp8266_07_uptime_human:
        friendly_name: Uptime esp8266_07
        value_template: >-
           {% macro human_time(seconds) -%}
             {%- set seconds = seconds|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'weeks': 60 * 60 * 24 * 7,
               'days': 60 * 60 * 24,
               'hours': 60 * 60,
               'minutes': 60,
               'seconds': 1,
             } -%}
           
             {%- set weeks = seconds // intervals.weeks -%}
             {%- set seconds = seconds % intervals.weeks -%}
             {{- comma() ~ weeks ~ ' week' ~ ('s' if weeks != 1) if weeks -}}
           
             {%- set days = seconds // intervals.days -%}
             {%- set seconds = seconds % intervals.days -%}
             {{- comma() ~ days ~ ' day' ~ ('s' if days != 1) if days -}}
           
             {%- set hours = seconds // intervals.hours -%}
             {%- set seconds = seconds % intervals.hours -%}
             {{- comma() ~ hours ~ ' hour' ~ ('s' if hours != 1) if hours -}}
           
             {%- set minutes = seconds // intervals.minutes -%}
             {{- comma() ~ minutes ~ ' minute' ~ ('s' if minutes != 1) if minutes -}}
           
             {%- set seconds = seconds % intervals.minutes -%}
             {{- comma() ~ seconds ~ ' second' ~ ('s' if seconds != 1) if seconds -}}
           {%- endmacro %}
           {{ human_time(states.sensor.esp8266_07_uptime.state | int * 60) }}

      esp8266_07_motion:
        friendly_name: esp07
        value_template: '{% if is_state("sensor.esp8266_07_pir", "1") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("sensor.esp8266_07_pir", "1") %}mdi:alert{% else %}mdi:eye-off{% endif %}'

      esp8266_07_motion_radar:
        friendly_name: Bad Radar
        value_template: '{% if is_state("sensor.esp8266_07_radar", "1") %}Bewegung erkannt!{% else %}Keine Bewegung.{% endif %}'
        icon_template: '{% if is_state("sensor.esp8266_07_radar", "1") %}mdi:alert{% else %}mdi:eye-off{% endif %}'


      esp07_motion_last_triggered:
        friendly_name: "Bad Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.sensor.esp8266_07_motion_radar.last_changed)|timestamp_custom('%H:%M:%S %d.%m.%Y') }}

### log motion to the file

notify:
    - name: esp07_radar_log
      platform: file
      filename: /home/homeassistant/log/esp07/radar.txt

### xmlstarlet wrapper
shell_command:
  update_rssfeed_motion_esp07: xmlstarlet ed -L   -a "//channel" -t elem -n item -v "" -s "//item[1]" -t elem -n title -v "Radar Bad" -s "//item[1]"  -t elem -n pubDate -v "`date`" -s "//item[1]" -t elem -n description -v "Bewegung im Bad!" -s "//item[1]" -t elem -n guid -v "GUID" -d "//item[position()>10]" /home/homeassistant/rssfeed/feed.xml

### Record motion  to a file (see notify)
automation:
  - alias: esp07 radar logfile
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.esp8266_07_motion_radar
        from: 'Keine Bewegung.'
        to: 'Bewegung erkannt!'
    action:
      - service: notify.esp07_radar_log
        data_template:
          message: >
            {{ as_timestamp(states.sensor.esp8266_07_motion_radar.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S: ') }} {{ states.sensor.esp8266_07_motion_radar.state }} (Radar Bad)
      - service: shell_command.update_rssfeed_motion_esp07


