########################################################################
## Packages / ESP32 #2                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:


    sensor.esp32_02_battery:
      icon: mdi:car-battery
      friendly_name: Batteriewert ESP32 02

    sensor.esp32_02_battery_state:
      friendly_name: Batteriestatus ESP32 02

    sensor.esp32_02_humidity:
      icon: mdi:water-percent
      friendly_name: Luftfeuchtigkeit

    sensor.esp32_02_temperature:
      icon: mdi:temperature-celsius
      friendly_name: Temperatur

#############
#  group    #
#############
group:
  esp_02:
    control: hidden
    icon: mdi:door
    name: Tempsensor
    entities:
      - sensor.esp32_02_battery
      - sensor.esp32_02_battery_state
      - sensor.esp32_02_temperature
      - sensor.esp32_02_humidity
      - sensor.esp32_02_temperature_last_changed
      - automation.benachrichtigung_batterie_esp32_02


#############
#  sensors  #
#############
sensor:

  - platform: mqtt
    name: "esp32_02_battery"
    state_topic: "testsensor/sensor/spannung_akku/state"
    unit_of_measurement: "V"
    qos: 0

  - platform: mqtt
    name: "esp32_02_humidity"
    state_topic: "testsensor/sensor/humidity/state"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "esp32_02_temperature"
    state_topic: "testsensor/sensor/temperature/state"
    qos: 0
    unit_of_measurement: "°C"

  - platform: template
    sensors:



      esp32_02_battery_state:
        value_template: "{{ 'Geladen ' if states.sensor.esp32_02_battery.state | float >3.3  else 'Leer' }}"
        icon_template: "{{ 'mdi:battery ' if states.sensor.esp32_02_battery.state | float >3.3  else 'mdi:battery-10' }}"

      esp32_02_temperature_last_changed:
        value_template: >-
          {{ as_timestamp(states.sensor.esp32_02_temperature.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}


### automation battery empty
automation:
  alias: benachrichtigung_batterie_esp32_02
  initial_state: False
  trigger:
    - platform: state
      entity_id: sensor.esp32_02_battery_state
      from: 'Geladen'
      to: 'Leer'
  action:
    - service: notify.pushbullet
      data_template:
        message: >
           {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
    - service: persistent_notification.create
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }}"
        message: >
            {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
        notification_id: "esp01_battery_notification"
