########################################################################
## Packages / ESP32 #1                                                ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
## Thanks to Merlin Schumacher                                        ##
## esp32 with basecamp (https://github.com/merlinschumacher/Basecamp) ##
########################################################################
homeassistant:
  customize:


    sensor.esp32_01_battery:
      icon: mdi:car-battery
      friendly_name: Batteriestatus ESP32 01

    sensor.esp32_01_battery_state:
      icon: mdi:car-battery
      friendly_name: Batteriestatus ESP32 01

    sensor.esp32_01_battery_value:
      icon: mdi:car-battery
      friendly_name: Batteriewert ESP32 01

    sensor.esp32_01_door_state:
      icon: mdi:door
      friendly_name: Wohnungstüre ELW

    sensor.esp32_01_door_motion:
      icon: mdi:door
      friendly_name: Wohnungstüre ELW

    sensor.esp32_01_motion_last_triggered:
      icon: mdi:door
      friendly_name: Letze Bewegung

#############
#  group    #
#############
group:

  esp_01:
    control: hidden
    icon: mdi:door
    name: Türsensor ELW
    entities:
#      - sensor.esp32_01_battery
      - sensor.esp32_01_battery_state
      - sensor.esp32_01_battery_value
#      - sensor.esp32_01_door_state
      - sensor.esp32_01_door_motion
      - sensor.esp32_01_motion_last_triggered


#############
#  sensors  #
#############
sensor:

  - platform: mqtt
    name: "esp32_01_battery"
    state_topic: "stat/tuere-elw/battery"
    qos: 0


  - platform: mqtt
    name: "esp32_01_battery_value"
    state_topic: "stat/tuere-elw/batteryvalue"
    unit_of_measurement: "mV"
    qos: 0


  - platform: mqtt
    name: "esp32_01_door_state"
    state_topic: "stat/tuere-elw/status"
    qos: 0


  - platform: template
    sensors:


      esp32_01_door_motion:
        value_template: '{% if is_state("sensor.esp32_01_door_state", "open") %}Türe geöffnet!{% else %}Türe geschlossen.{% endif %}'
        icon_template: '{% if is_state("sensor.esp32_01_door_state", "open") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'

      esp32_01_battery_state:
        value_template: '{% if is_state("sensor.esp32_01_battery", "full") %}Geladen{% else %}Leer{% endif %}'
        icon_template: '{% if is_state("sensor.esp32_01_battery", "full") %}mdi:battery{% else %}mdi:battery-10{% endif %}'

      esp32_01_motion_last_triggered:
        value_template: >-
          {{ as_timestamp(states.sensor.esp32_01_door_motion.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}


### automation battery empty
automation:
  alias: benachrichtigung_batterie_esp_01
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.esp32_01_battery
      from: 'full'
      to: 'empty'
  action:
    - service: notify.pushbullet
      data_template:
        message: >
           {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
    - service: persistent_notification.create
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }}"
        message: >
            {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Achtung!: {{ trigger.to_state.attributes.friendly_name }} Akku aufladen!
        notification_id: "esp01_battery_notification" 
