##############################################################
### Packages / esphome update                              ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:

sensor:
  - platform: command_line
    scan_interval: 3600
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/esphome/json').json()['info']['version'])"
    name: esphome_release

automation:
  - alias: esphome_release_update_notification
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.esphome_release
    action:
      - service: notify.pushbullet
        data:
          message: '{{ states.sensor.date_time.state }}: esphome V{{ states.sensor.esphome_release.state }} released!'
