########################################################################
## Packages / First Floor                                             ##
## @bl0rp - https://github.com/bl0rp/Home-Assistant-Config            ##
########################################################################
homeassistant:
  customize:
    script.1og_lampen_an:
      friendly_name: Alle Lampen an!
      icon: mdi:lamp
    script.1og_lampen_aus:
      friendly_name: Alle Lampen aus!
      icon: mdi:flashlight-off






###
#See Sensor Package esp8266_01 and esp8266_03#
###

####################################
### automation lights auto on/off ##
####################################

automation:
###
# Turn on Automation before next sunset
###
  - alias: "restart_automations_before_next_sunset"
    id: restart_automations_before_next_sunset
    initial_state: true
    trigger:
      platform: time
      at: "15:00:00"
    action:
      - service: automation.turn_on
        entity_id: automation.first_floor_lights_on_dusk_brightness

#Esszimmer on/off

###
# on at sunset
###

  - alias: "first_floor_lights_on_dusk_brightness"
    id: first_floor_lights_on_dusk_brightness

    trigger:
      - platform: numeric_state
        entity_id: sensor.esp32_13_brightness_bh1750
        below: 275
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2
    condition:
      - condition: time
        before: "22:00:00"
        after: "16:00:00"
      - condition: numeric_state
        entity_id: sensor.esp32_13_brightness_bh1750
        below: 275
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2
      - condition: template
        value_template: "{{ trigger.from_state.state != 'unknown' }}"

    action:
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_09
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_10
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_11
      - service: notify.telegram_christoph
        data_template:
          message: >
            {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Lampen an im 1OG
            Lux Wiga: {{ states('sensor.esp32_13_brightness_bh1750') }}
            elevation: {{ state_attr('sun.sun', 'elevation') }}
            dusk: {{as_timestamp(states.sun.sun.attributes.next_dusk)|timestamp_custom('%H:%M:%S')}}
            sunset: {{as_timestamp(states.sun.sun.attributes.next_setting)|timestamp_custom('%H:%M:%S')}}
      - service: automation.turn_on
        entity_id: automation.first_floor_lamp_living_room_on
      - service: automation.turn_off
        entity_id: automation.first_floor_lights_on_dusk_brightness
###
# off at 22:00
###

  - alias: "Lampe Esszimmer um 22 Uhr ausschalten"
    initial_state: true
    trigger:
      - platform: time_pattern
        hours: 22
        minutes: 00
        seconds: 00
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_09
      - service: switch.turn_off
        entity_id: switch.sonoff_10
      - service: switch.turn_off
        entity_id: switch.sonoff_11

#Stehlampe on/off

###
# on after 1st movement
###

  - alias: "first_floor_lamp_living_room_on"
    id: first_floor_lamp_living_room_on
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.esp8266_01_pir
        from: '0'
        to: '1'
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff_12
      - service: notify.pushbullet
        data_template:
          message: >
             {{ states.sensor.date_time.state }} {{ trigger.to_state.attributes.friendly_name }} hat das erste Mal nach Sonnenuntergang ausgelöst und die Stehlampe wurde angeschaltet!
      - service: automation.turn_off
        entity_id: automation.first_floor_lamp_living_room_on

# off 20m after last movement

  - alias: "first_floor_lamp_living_room_off"
    id: first_floor_lamp_living_room_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.esp8266_01_pir
        from: '1'
        to: '0'
        for:
          minutes: 20
    condition:
      - condition: time
        after: "22:00:00"
        before: "01:00:00"
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_12
      - service: notify.pushbullet
        data_template:
          message: >
             {{ states.sensor.date_time.state }}  letze bewergung vor 20 min und lampe aus





#############
### script ##
#############
script:
###
# all lights on and off
###


  1og_lampen_an:
    sequence:
       - service: switch.turn_on
         entity_id: switch.sonoff_11
       - service: switch.turn_on
         entity_id: switch.sonoff_12
       - service: switch.turn_on
         entity_id: switch.sonoff_09
       - service: switch.turn_on
         entity_id: switch.sonoff_10
  1og_lampen_aus:
    sequence:
       - service: switch.turn_off
         entity_id: switch.sonoff_11
       - service: switch.turn_off
         entity_id: switch.sonoff_12
       - service: switch.turn_off
         entity_id: switch.sonoff_09
       - service: switch.turn_off
         entity_id: switch.sonoff_10
