##############################################################
### Packages / github sensor                               ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:

sensor:
  - platform: github
    access_token: !secret github_token
    repositories:
      - path: 'home-assistant/home-assistant'
      - path: 'bl0rp/Home-AssistantConfig'
