##############################################################
### Packages / ISS                                         ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:

#################
### Customize ###
#################

  customize:

    camera.iss:
      friendly_name: Position ISS
      icon: mdi:radar
    sensor.iss_next_rise:
      friendly_name: "Nächster Überflug"
      icon: mdi:rocket
    sensor.iss_visible:
      friendly_name: ISS sichtbar?



#################
###  ISS MAP  ###
#################
camera:
  - platform: generic
    name: ISS
    still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=4&size=865x512&maptype=mapnik&markers={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }},lightblue
    limit_refetch_to_url_change: true

group:
  iss:
    name: ISS
    icon: mdi:rocket
    entities:
      - sensor.iss_visible
      - sensor.next_launch
      - sensor.iss_next_rise
      - camera.iss



###############
### Sensors ###
###############
binary_sensor:
  - platform: iss

sensor:
  - platform: launch_library


  - platform: template
    sensors:
      iss_visible:
        value_template: "{% if states.binary_sensor.iss.state  == On %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states.binary_sensor.iss.state  == On  %}mdi:rocket{% else %}mdi:eye-off{% endif %}"

      iss_next_rise:
        value_template: >-
          {{ as_timestamp(states.binary_sensor.iss.attributes.next_rise)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}
