##############################################################
### Packages / MQTT via Cellular                           ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################
homeassistant:
  customize:
    sensor.phonebatt:
      friendly_name: "Pixel2"
      icon: mdi:cellphone

sensor:
#all 15min current battery level is sent
  - platform: mqtt
    name: "phonebatt"
    state_topic: "pixel2/battery"
    unit_of_measurement: "%"
    icon: mdi:cellphone
    force_update: true
# tasker home sensor for presence detection
  - platform: mqtt
    name: "tasker_home_connection"
    state_topic: "pixel2/presence/update"
  - platform: mqtt
    name: "tasker_home"
    state_topic: "pixel2/presence"
