#################################################################################
### Packages / Scene Selector                                                 ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig                    ###
#################################################################################
homeassistant:
  customize:
    automation.motion_zwave_sunset_flur_dimlight:
      friendly_name: Licht im Flur bei Bewegung an?
      icon: mdi:eye-circle-outline

###############################################
## Input Select                               #
###############################################


input_select:
  elw_scene:
    name: Welche Scene?
    icon: mdi:theme-light-dark
    options:
      - Keine
      - Letzte
      - ELW Relax
      - ELW Hell
      - ELW Aus
      - Schlafzimmer Relax
      - Schlafzimmer Hell
      - Schlafzimmer Aus
      - Flur Relax
      - Flur Hell
      - Flur Aus
  tuerlicht:
    name: Wie lange soll das Türlicht brennen?
    icon: mdi:timer
    options:
     - 5
     - 15
     - 30
     - 45
     - 60



###############################################
## Sensor                                     #
###############################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/current_scene_elw_set"
    name: homeassistant_mqtt_scene_elw_set
  - platform: mqtt
    state_topic: "homeassistant/current_timer_tuerlicht_elw_set"
    name: current_timer_tuerlicht_elw_set
###############################################
## Automation                                 #
###############################################

#Store Last used scene
automation:
  - id: set_elw_scene
    alias: set_elw_scene
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.elw_scene
    condition:
      condition: template
      value_template: "{{ states('input_select.elw_scene') not in ['Keine','Letzte'] }}"

    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ states('input_select.elw_scene')|replace(' ', '_')}}"
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/current_scene_elw_set"
          retain: true
          payload: "{{ states('input_select.elw_scene')|replace(' ', '_')}}"
      - service: input_select.select_option
        entity_id: input_select.elw_scene
        data:
          option: 'Keine'

  - alias: repeat_last_elw_scene
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_select.elw_scene
        from: Keine
        to: Letzte
    # condition:
    #   condition: template
    #   value_template: "{{ not is_state('input_select.elw_scene', 'Letzte')}}"
    action:
      service: input_select.select_option
      entity_id: input_select.elw_scene
      data_template:
        option: "{{ states('sensor.homeassistant_mqtt_scene_elw_set')|replace('_', ' ')}}"

  - id: set_current_timer_tuerlicht_elw
    alias: set_current_timer_tuerlicht_elw
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.tuerlicht
    action:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/current_timer_tuerlicht_elw_set"
          retain: true
          payload: "{{ states('input_select.tuerlicht') }}"

  - alias: restore_current_timer_tuerlicht_elw
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: input_select.select_option
      entity_id: input_select.tuerlicht
      data_template:
        option: "{{ states('sensor.current_timer_tuerlicht_elw_set')| title}}"


  - alias: motion_zwave_sunset_flur_dimlight
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      from: '0'
      to: '8'
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: state
        entity_id: input_boolean.chrisbluetooth
        state: "on"
      - condition: state
        entity_id: light.flur
        state: "off"
    action:
      - service: scene.turn_on
        entity_id: scene.flur_relax
      - delay: '{{ states.input_select.tuerlicht.state | int }}'
      - service: scene.turn_on
        entity_id: scene.flur_aus

#Group for main view.yaml

group:
  elw_scene_select:
    name: Licht ELW
    view: no
    icon: mdi:brush
    control: hidden
    entities:
      - input_select.elw_scene
      - input_select.tuerlicht
      - light.flur
      - light.schlafzimmer
      - switch.11011_a
      - switch.11011_b
      - switch.11011_c
      - automation.motion_zwave_sunset_flur_dimlight
