#################################################################################
### Packages / Scene Selector                                                 ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig                    ###
#################################################################################


###############################################
## Input Select                               #
###############################################


input_select:
  elw_scene:
    name: Licht in der ELW
    icon: mdi:theme-light-dark
    options:
      - Aktuelles beibehalten
      - ELW Relax
      - ELW Hell
      - ELW Aus
      - Schlafzimmer Relax
      - Schlafzimmer Hell
      - Schlafzimmer Aus
      - Flur Relax
      - Flur Hell
      - Flur Aus

###############################################
## Sensor                                     #
###############################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/current_scene_elw_set"
    name: homeassistant_mqtt_scene_elw_set
###############################################
## Automation                                 #
###############################################

automation:
  #manual change of the theme
  - id: set_elw_scene
    alias: set_elw_scene
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.elw_scene
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.elw_scene', 'Aktuelles beibehalten') }}"
    action:
      #Set the theme
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ states('input_select.elw_scene')|replace(' ', '_') }}"
      #Send and save theme via mqtt
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/current_scene_elw_set"
          retain: true
          payload: "{{ states('input_select.elw_scene')|replace(' ', '_') }}"
  #Restore old value
  - alias: restore_elw_scene
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: input_select.select_option
      entity_id: input_select.elw_scene
      data_template:
        option: "{{ states('sensor.homeassistant_mqtt_scene_elw_set')|replace('_', ' ')| title}}"
#Group for main view.yaml
group:
  elw_scene_select:
    name: Licht ELW
    view: no
    icon: mdi:brush
    entities:
      - input_select.elw_scene
