##############################################################
### Packages / send data esps                              ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:


#Turn on/off the ESP / Automations  while using the Computer
automation:
  - alias: auto_on_lcd
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - sensor.sonoff02_use
      to: 'Ja'
      for:
        seconds: 30
    action:
      - service: switch.turn_on
        entity_id: switch.11001_a
      - service: automation.turn_on
        entity_id: automation.nuc_load_to_led


  - alias: auto_off_lcd
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - sensor.sonoff02_use
      to: 'Nein'
      for:
        seconds: 15
    action:
      - service: switch.turn_off
        entity_id: switch.rote_led
      - service: switch.turn_off
        entity_id: switch.gelbe_led
      - service: switch.turn_off
        entity_id: switch.gruene_led
      - service: switch.turn_on
        entity_id: switch.esp8266_led_oled_shutdown
      - service: switch.turn_on
        entity_id: switch.esp8266_lcd_shutdown
      - delay: 00:00:05
      - service: switch.turn_off
        entity_id: switch.11001_a
      - service: automation.turn_off
        entity_id: automation.nuc_load_to_led

  - alias: nuc_load_to_led
    initial_state: False
    trigger:
      - platform: state
        entity_id: sensor.load_1m
    action:
      - service_template: >-
          {% if 0 <= trigger.to_state.state|float and  trigger.to_state.state|float < 0.2 %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        data:
          entity_id: switch.gruene_led

      - service_template: >-
          {% if 0.2 <= trigger.to_state.state|float < 0.6 %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        data:
          entity_id: switch.gelbe_led

      - service_template: >-
          {% if 0.6 <= trigger.to_state.state|float < 30.0 %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        data:
          entity_id: switch.rote_led
