##############################################################
### Packages / Sensor Update Warning                       ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:
  customize:
    sensor.phonebatt_watch:
      friendly_name: Handyakku
    sensor.esp32_02_watch:
      friendly_name: DHT Carport
    sensor.esp32_03_watch:
      friendly_name: BMP ELW
###### STATE CARD for views.yaml

group:
  sensor_warn:
    control: hidden
    icon: mdi:ethernet-cable
    name: Sensorwarn
    entities:
    - sensor.phonebatt
    - sensor.phonebatt_debug
    - sensor.phonebatt_debug2
    - sensor.phonebatt_watch
    - sensor.esp32_02_temperature
    - sensor.esp32_02_debug
    - sensor.esp32_02_debug2
    - sensor.esp32_02_watch
    - sensor.esp32_03_temperature
    - sensor.esp32_03_debug
    - sensor.esp32_03_debug2
    - sensor.esp32_03_watch
    - automation.notify_sensor_update
sensor:

###### warning if battery powered sensor does not update
#battery mobile
  - platform: template
    sensors:
      phonebatt_watch:
        value_template: "{% if as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.phonebatt.last_updated) > 120*60 %}true{% else %}false{% endif %}"
      phonebatt_debug:
        value_template: "{{ as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.phonebatt.last_updated)  }}"
      phonebatt_debug2:
        value_template: "{{ states.sensor.phonebatt.last_updated  }}"
#outdoor sensor 2
  - platform: template
    sensors:
      esp32_02_watch:
        value_template: "{% if as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.esp32_02_temperature.last_updated) > 120*60 %}true{% else %}false{% endif %}"
      esp32_02_debug:
        value_template: "{{ as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.esp32_02_temperature.last_updated)  }}"
      esp32_02_debug2:
        value_template: "{{ states.sensor.esp32_02_temperature.last_updated  }}"
#outdoor sensor 3
  - platform: template
    sensors:
      esp32_03_watch:
        value_template: "{% if as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.esp32_03_temperature.last_updated) > 120*60 %}true{% else %}false{% endif %}"
      esp32_03_debug:
        value_template: "{{ as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.esp32_03_temperature.last_updated)  }}"
      esp32_03_debug2:
        value_template: "{{ states.sensor.esp32_03_temperature.last_updated  }}"
#################################################
### Notify when a Sensor does not update      ###
#################################################
automation:
  - alias: notify_sensor_update
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.phonebatt_watch
          - sensor.esp32_02_watch
          - sensor.esp32_03_watch
        to: 'true'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
    - service: notify.pushbullet
      data_template:
        message: >
          NO UPDATE: {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Sensor {{ trigger.to_state.attributes.friendly_name }}
