##############################################################
### Packages / Sensor Update Warning                       ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:
  customize:
    sensor.phonebatt_watch:
      friendly_name: Handyakku Pixel4XL



##### notify component -> logfile
notify:
    - name: sensor_watch_log
      platform: file
      filename: /home/homeassistant/log/sensor_update.txt

sensor:

###### warning if battery powered sensor does not update
#battery mobile 2hours
  - platform: template
    sensors:
      phonebatt_watch:
        entity_id: sensor.time
        value_template: "{% if as_timestamp(states.sensor.date_time.last_updated) - as_timestamp(states.sensor.tasker_pixel4xl_battery.last_updated) > 120*60 %}true{% else %}false{% endif %}"




#################################################
### Notify when a Sensor does not update      ###
#################################################
automation:
  - alias: notify_sensor_update
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.phonebatt_watch
        to: 'true'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
    - service: notify.telegram_christoph
      data_template:
        message: >
          NO UPDATE: {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Sensor {{ trigger.to_state.attributes.friendly_name }}
    - service: notify.sensor_watch_log
      data_template:
        message: >
          NO UPDATE: {{ now().strftime('%d.%m.%Y %H:%M:%S') }} Sensor {{ trigger.to_state.attributes.friendly_name }}
