##############################################################
### Packages / sonoff5                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks to cnrd                                         ###
### https://github.com/cnrd                                ###
### Inspired by mihalski                                   ###
### https://github.com/mihalski/homeassistant-config       ###
##############################################################

homeassistant:

  customize:
    switch.sonoff5:
      friendly_name: Trockner
      icon: mdi:fan
      persistent: true
    sensor.sonoff5_ipv4:
      friendly_name: IPv4
      icon: mdi:server-network
    sensor.sonoff5_momentane_leistung:
      friendly_name: Aktuelle Leistung
      icon: mdi:power-plug
    sensor.sonoff5_spannung:
      friendly_name: Spannung
      icon: mdi:flash
    sensor.sonoff5_stromstaerke:
      friendly_name: Stromstärke
      icon: mdi:flash
    sensor.sonoff5_max_load:
      friendly_name: Maximale Leistung
      icon: mdi:fire
    sensor.sonoff5_kosten_heute:
      friendly_name: Kosten Heute
      icon: mdi:currency-eur
    sensor.sonoff5_kosten_gestern:
      friendly_name: Kosten Gestern
      icon: mdi:currency-eur
    sensor.sonoff5_kosten_gesamt:
      friendly_name: Gesamtkosten
      icon: mdi:currency-eur
    sensor.sonoff5_verbrauch_heute:
      friendly_name: Vebrauch Heute
      icon: mdi:chart-line
    sensor.sonoff5_verbrauch_gestern:
      friendly_name: Vebrauch Gestern
      icon: mdi:chart-line
    sensor.sonoff5_gesamtverbrauch:
      friendly_name: Gesamtverbrauch
      icon: mdi:chart-line
    script.del_sonoff5_power_log:
      friendly_name: Maximale Leistung zurücksetzen
      icon: mdi:eraser
    automation.dryer_start:
      friendly_name: Trockenvorgang begonnen
      icon: mdi:washing-machine
    automation.dryer_done:
      friendly_name: Benachrichtigung Trockenvorgang beendet
      icon: mdi:washing-machine
    input_boolean.dryer_switch:
      friendly_name: Trockenvorgang aktiv?

group:
  sonoff5:
    control: hidden
    name: Sonoff 5
    view: no
    entities:
      - switch.sonoff5
      - sensor.sonoff5_ipv4
      - sensor.sonoff5_use
      - sensor.sonoff5_momentane_leistung
      - sensor.sonoff5_spannung
      - sensor.sonoff5_stromstaerke
      - sensor.sonoff5_max_load
      - sensor.sonoff5_verbrauch_heute
      - sensor.sonoff5_verbrauch_gestern
      - sensor.sonoff5_gesamtverbrauch
      - sensor.sonoff5_kosten_heute
      - sensor.sonoff5_kosten_gestern
      - sensor.sonoff5_kosten_gesamt
      - script.del_sonoff5_power_log
      - input_boolean.dryer_switch
      - automation.dryer_start
      - automation.dryer_done

sensor:

### Reading the values from the tasmota mqtt string

  - platform: mqtt
    name: "sonoff5 Verbrauch Heute"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 Verbrauch Gestern"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 Gesamtverbrauch"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 Momentane Leistung"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 Spannung"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 Stromstaerke"
    state_topic: "tele/sonoff5/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: "A"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

  - platform: mqtt
    name: "sonoff5 IPv4"
    state_topic: "tele/sonoff5/INFO2"
    value_template: "{{ value_json.IPAddress }}"
    availability_topic: "tele/sonoff5/LWT"
    payload_available: "online"
    payload_not_available: "offline"

### Calculating cost based on the local prive per kWh

  - platform: template
    sensors:
      sonoff5_kosten_heute:
        friendly_name: Kosten Heute
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff5_verbrauch_heute.state  | multiply(0.2657) | round(2) }}

      sonoff5_kosten_gestern:
        friendly_name: Kosten Gestern
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff5_verbrauch_gestern.state  | multiply(0.2657) | round(2) }}

      sonoff5_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{ states.sensor.sonoff5_gesamtverbrauch.state  | multiply(0.2657) | round(2) }}

### Usage sensor for other scripts/automations

      sonoff5_use:
        friendly_name: "Vebraucher aktiv?"
        value_template: "{% if states('sensor.sonoff5_momentane_leistung') | int > 30 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.sonoff5_momentane_leistung') | int > 30 %}mdi:flash{% else %}mdi:flash-off{% endif %}"


### Reading the highest value in the power log file ( see automation)

  - platform: command_line
    name: 'sonoff5_max_load'
    command: "grep -E '[0-9]+' /home/homeassistant/log/sonoff5/power.txt| sort -rn | head -n 1"
    unit_of_measurement: "W"
    scan_interval: 15

### log power to the logfile

notify:
    - name: sonoff5_power_log
      platform: file
      filename: /home/homeassistant/log/sonoff5/power.txt

### main switch on/off

switch:
  - platform: mqtt
    name: "sonoff5"
    state_topic: "stat/sonoff5/POWER"
    command_topic: "cmnd/sonoff5/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

### Input boolen for washing state

input_boolean:
  dryer_switch:
    initial: off


### Record all power levels to a file (see notify)
automation:
  - alias: sonoff5 Load logfile
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff5_momentane_leistung
    action:
      - service: notify.sonoff5_power_log
        data_template:
          message: >
            {{ states.sensor.sonoff5_momentane_leistung.state }}

### Notification when dryer is done
  - alias: 'dryer_Start'
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff5_use
        from: 'Nein'
        to: 'Ja'
        for:
          minutes: 2
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dryer_switch
  
  - alias: 'dryer_Done'
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.sonoff5_use
        from: 'Ja'
        to: 'Nein'
        for:
          minutes: 5
    condition:
        condition: state
        entity_id: input_boolean.dryer_switch
        state: 'on'
    action:
      - service: notify.pushbullet
        data_template:
          message: "{{ now().strftime('%d.%m.%Y %H:%M:%S') }}:Der Trockner verbraucht keinen Strom mehr."
      - service: notify.pushbullet_traude
        data_template:
          message: "{{ now().strftime('%d.%m.%Y %H:%M:%S') }}:Der Trockner verbraucht keinen Strom mehr."
      - service: input_boolean.turn_off
        entity_id: input_boolean.dryer_switch

### Delete the logfile (reset the maximum power sensor)

script:
  del_sonoff5_power_log:
     sequence:
       - service: shell_command.del_sonoff5_power_log

shell_command:
  del_sonoff5_power_log: rm /home/homeassistant/log/sonoff5/power.txt && touch /home/homeassistant/log/sonoff5/power.txt && chown -R -v homeassistant:homeassistant /home/homeassistant/log/sonoff5/power.txt