#################################################################################
### Packages / Theme Selector                                                 ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig                    ###
### Inspired by BurnsHA (https://www.youtube.com/watch?v=h1h8FFy9_Co&t        ###
#################################################################################

###############################################
## Frontend & Themes                          #
###############################################
frontend:
#  javascript_version: latest
  themes:
    dark:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
      # Text colors
      primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value
      # Background colors
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider
      # Table rows
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative
      # Nav Menu
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       # Navigation menu selection
      # Paper card
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               # Popup item select
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here
      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#E45E65'
      google-green-500: '#39E949'
    dark_red:
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b"
      paper-card-header-color: "var(--paper-item-icon-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
    mono_light:
      # MyVar
      huesat: '0, 0%,'
      # Primary Color
      primary-color: 'hsl(var(--huesat) 80%)'
      dark-primary-color: 'hsl(var(--huesat) 20%)'
      light-primary-color: 'hsl(var(--huesat) 90%)'
      accent-color: 'hsl(var(--huesat) 30%)'
      # Backgrounds
      primary-background-color: 'var(--primary-color)'
      secondary-background-color: 'hsl(var(--huesat) 86%)'
      paper-listbox-background-color: 'var(--primary-color)'
      paper-card-background-color: 'hsl(var(--huesat) 90%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 88%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 90%)'
      # Devider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      dark-secondary-opacity: '0.4'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 46%)'
      text-primary-color: 'hsl(var(--huesat) 46%)'
      secondary-text-color: 'hsl(var(--huesat) 56%)'
      disabled-text-color: 'hsl(var(--huesat) 30%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 5%)'
      sidebar-text-color: 'hsl(var(--huesat) 5%)'
      paper-card-header-color: 'hsl(hsl(var(--huesat) 50%)'
      paper-button-ink-color: 'hsl(hsl(var(--huesat) 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '500'
      paper-font-body1_-_font-weight: '500'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 40%)'
      paper-grey-200: 'hsl(var(--huesat) 72%)'
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 70%)'
      paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'hsl(var(--huesat) 70%)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 100%, 0.2)'
      paper-item-selected_-_color: 'hsl(var(--huesat) 20%)'
      paper-tabs-selection-bar-color: 'hsl(var(--huesat) 70%)'
      paper-tab-ink: 'hsl(var(--huesat) 70%)'
      paper-input-container-color: 'hsl(var(--huesat) 66%)'
      # Labels
      label-badge-red: 'hsl(var(--huesat) 80%)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'hsl(var(--huesat) 82%)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 3px hsla(var(--huesat) 91%, 0.2)'
      shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 3px hsla(var(--huesat) 91%, 0.2)'
      paper-input-container-shared-input-style_-_background: '#000'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--huesat) 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 66%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 85%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 80%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--huesat) 45%)'
      paper-slider-knob-start-color: 'hsl(var(--huesat) 60%)'
      paper-slider-pin-color:  'hsl(var(--huesat) 60%)'
      paper-slider-active-color:  'hsl(var(--huesat) 60%)'
      paper-slider-container-color: 'hsl(var(--huesat) 76%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 10%)'
      paper-slider-disabled-active-color: 'hsl(var(--huesat) 75%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--huesat) 75%)'
      #Toast
      paper-toast-color: 'hsl(var(--huesat) 45%)'
      paper-toast-background-color: 'hsl(var(--huesat) 90%)'

    mono_night:
      # MyVariables
      base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
      base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
      # MyVar
      huesat: 'var(--base-hue), var(--base-sat),'
      # Primary Color
      primary-color: 'hsl(var(--huesat) 20%)'
      # Backgrounds
      primary-background-color: 'var(--primary-color)'
      secondary-background-color: 'hsl(var(--huesat) 16%)'
      paper-listbox-background-color: 'var(--primary-color)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      # Devider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 60%)'
      text-primary-color: 'hsl(var(--huesat) 60%)'
      secondary-text-color: 'hsl(var(--huesat) 60%)'
      disabled-text-color: 'hsl(var(--huesat) 70%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
      sidebar-text-color: 'hsl(var(--huesat) 90%)'
      paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '500'
      paper-font-body1_-_font-weight: '500'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 50%)'
      paper-grey-200: 'hsla(var(--huesat) 26%)'
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 30%)'
      paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'var(--paper-item-icon-color)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
      # Labels
      label-badge-red: 'hsla(0, 0%, 0%, 0)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'var(--paper-card-background-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
      shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-container-color: 'hsl(var(--huesat) 28%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
      paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'

    solarized:
      primary-color: "#2aa198"
      disabled-text-color: "#859900"
      divider-color: "#586e75" #"rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#002b36"
      paper-grey-200: "#586e75"
      paper-item-icon-color: "#b58900"
      paper-listbox-background-color: "#002b36"
      paper-listbox-color: "#b58900"
      primary-background-color: "#073642"
      primary-text-color: "#839496"
      secondary-background-color: "#073642"
      secondary-text-color: "#859900"
      text-primary-color: "#839496"
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#cb4b16"
      paper-grey-50: "#b58900"
      paper-item-icon-active-color: "#dc322f"
      paper-item-icon_-_color: "#FF00FF"   # no clue
      paper-slider-active-color: "#dc322f"
      paper-slider-knob-color: "#dc322f"
      paper-slider-knob-start-color: "#b58900"
      paper-slider-pin-color: "#FF00FF"  # no clue
      paper-slider-secondary-color: "#dc322f"
      paper-toggle-button-checked-ink-color: "#dc322f"
      paper-toggle-button-checked-button-color: "#dc322f"
      paper-toggle-button-checked-bar-color: "#cb4b16"
      paper-toggle-button-unchecked-bar-color: "#b58900"
      table-row-background-color: "#002b36"
      table-row-alternative-background-color: "#073642"
      google-red: "#dc322f"
      google-green: "#859900"
      google-blue: "#268bd2"
      google-yellow: "#b58900"
      accent-color: "#cb4b16"
      paper-green: "#859900"
      paper-blue: "#268bd2"
      paper-orange: "#cb4b16"

###############################################
## Input Select                               #
###############################################

    #List all themes from the themes from above (' ' becomes _ and everything is lowered)

input_select:
  hass_theme:
    name: Welches Theme darf es sein?
    icon: mdi:theme-light-dark
    options:
      # "Aktuelles beibehalten" means "Keep selected"
      - Aktuelles beibehalten
      - Default
      - Dark Red
      - Solarized
      - Mono Night
      - Mono Light
###############################################
## Sensor                                     #
###############################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/current_theme_set"
    name: homeassistant_mqqt_theme_set
###############################################
## Automation                                 #
###############################################

automation:
  #manual change of the theme
  - id: set_hass_theme
    alias: set_hass_theme
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.hass_theme
    condition:
      #Don't do anything when selecting a certain Value ("Aktuelles...")
      condition: template
      value_template: "{{ not is_state('input_select.hass_theme', 'Aktuelles beibehalten') }}"
    action:
      #Set the theme
      - service: frontend.set_theme
        data_template:
          name: "{{ states('input_select.hass_theme')|lower|replace(' ', '_') }}"
      #Send and save theme via mqtt
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/current_theme_set"
          retain: true
          payload: "{{ states('input_select.hass_theme')|lower|replace(' ', '_') }}"
  #Restore old value
  - alias: set_theme
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: input_select.select_option
      entity_id: input_select.hass_theme
      data_template:
        option: "{{ states('sensor.homeassistant_mqqt_theme_set')|replace('_', ' ')| title}}"
#Group for main view.yaml
group:
  theme:
    name: Themes
    view: no
    icon: mdi:brush
    entities:
      - input_select.hass_theme
