#################################################################################
### Packages / Theme Selector                                                 ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig                    ###
### Inspired by BurnsHA (https://www.youtube.com/watch?v=h1h8FFy9_Co&t        ###
#################################################################################

###############################################
## Input Select                               #
###############################################

    #List all themes from the themes from above (' ' becomes _ and everything is lowered)

input_select:
  hass_theme:
    name: Welches Theme darf es sein?
    icon: mdi:theme-light-dark
    options:
      # "Aktuelles beibehalten" means "Keep selected"
      - Aktuelles beibehalten
      - Default
      - Clear
      - Dark
      - Dark Night
      - Dark Red
      - Solarized
      - Mono Night
      - Mono Light
      - Material Dark
      - AMOLED Blue
      - Dark Orange
      - Noctis
###############################################
## Sensor                                     #
###############################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/current_theme_set"
    name: homeassistant_mqtt_theme_set
###############################################
## Automation                                 #
###############################################

automation:
  #manual change of the theme
  - id: set_hass_theme
    alias: set_hass_theme
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.hass_theme
    condition:
      #Don't do anything when selecting a certain Value ("Aktuelles...")
      condition: template
      value_template: "{{ not is_state('input_select.hass_theme', 'Aktuelles beibehalten') }}"
    action:
      #Set the theme
      - service: frontend.set_theme
        data_template:
          name: "{{ states('input_select.hass_theme')|lower|replace(' ', '_') }}"
      #Send and save theme via mqtt
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/current_theme_set"
          retain: true
          payload: "{{ states('input_select.hass_theme')|lower|replace(' ', '_') }}"
  #Restore old value
  - alias: set_theme
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: frontend.set_theme
        data_template:
          name: "{{ states('input_select.hass_theme')|lower|replace(' ', '_') }}"
