##############################################################
### Packages / Utilities                                   ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
### Thanks 2 Norien                                        ###
### https://github.com/Norien/Home-Assistant-Config/       ###
##############################################################

homeassistant:
  customize:
    script.update_ha:
      friendly_name: Update Home Assistant
      icon: mdi:package-variant
    script.restart_ha:
      friendly_name: Restart Home Assistant
      icon: mdi:restart
    script.clear_log:
      friendly_name: 'Logfile löschen'
      icon: mdi:eraser
    script.clear_tts_cache:
      friendly_name: 'TTS Cache löschen'
      icon: mdi:shredder
    sensor.last_commit:
      icon: mdi:github
    sensor.last_backup:
      icon: mdi:backup-restore


script:
  update_ha:
    sequence:
      - service: tts.clear_cache
      - service: shell_command.update_ha
  restart_ha:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.restarts
      - service: tts.clear_cache
      - service: shell_command.del_log
      - service: shell_command.restart_ha
  clear_log:
     sequence:
       - service: shell_command.del_log
  clear_tts_cache:
    sequence:
      - service: tts.clear_cache

#########################################################################
sensor:
###### Latest github Commit
  - platform: command_line
    command: "python /home/homeassistant/script/latest_commit.py"
    name: 'Last Commit'
    scan_interval: 60

###### Latest config backup
  - platform: command_line
    command: "sudo python /home/homeassistant/script/latest_backup.py"
    name: 'Last Backup'
    scan_interval: 60


shell_command:
  update_ha: 'sudo bash /home/homeassistant/script/update_ha.sh </dev/null >> /home/homeassistant/log/update_ha.log 2>&1 &'
  restart_ha: 'sudo hassctl restart'
  del_log: rm /home/homeassistant/.homeassistant/home-assistant.log && touch /home/homeassistant/.homeassistant/home-assistant.log && chown -R -v homeassistant:homeassistant /home/homeassistant/.homeassistant/home-assistant.log
