##############################################################
### Packages / Waste Reminder                              ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################


homeassistant:
  customize:
    sensor.next_waste:
      friendly_name: "Nächste Leerung Mülltonnen"
      icon: mdi:delete-empty
    automation.waste_alert_12h:
      friendly_name: "Benachrichtigung Mülltonnen Morgen"
      icon: mdi:delete-empty
    automation.waste_alert_today:
      friendly_name: "Benachrichtigung Mülltonnen Heute"
      icon: mdi:delete-empty





sensor:
#template sensor for calc. unixtime -> automation
  - platform: template
    sensors:
      cal_alert_time_waste:
        value_template: >-
          {{ (as_timestamp(states.calendar.abfallwirtschaft_stuttgart.attributes.start_time) - as_timestamp(now()) )|int }}

# show next calendar entry
  - platform: template
    sensors:
      next_waste:
        value_template: >-
          {{(as_timestamp(states.calendar.abfallwirtschaft_stuttgart.attributes.start_time))|timestamp_custom('%d.%m.%Y') }} {{states.calendar.abfallwirtschaft_stuttgart.attributes.message|replace ('01-wöchentl.','')|replace ('02-wöchentl.','')|replace ('03-wöchentl.','')}}




automation:
#update tempalte sensors
  - alias: 'waste_template_sensors_update'
    trigger:
      - platform: time_pattern
        minutes: '/2'
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.cal_alert_time_waste

#Restmüll 12h
  - alias: waste_alert_12h
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.cal_alert_time_waste
        below: 50400
        above: 50200
    action:
      - service: notify.pushbullet
        data_template:
          title: 'Erinnerung Müllabfuhr Morgen'
          message: >
              {{(as_timestamp(states. calendar.abfallwirtschaft_stuttgart.attributes.start_time))|timestamp_custom('%d.%m.%Y') }} {{states.calendar.abfallwirtschaft_stuttgart.attributes.message|replace ('01-wöchentl.','')|replace ('02-wöchentl.','')|replace ('03-wöchentl.','')}}
      - service: notify.pushbullet_traude
        data_template:
          title: 'Erinnerung Müllabfuhr Morgen'
          message: >
              {{(as_timestamp(states.calendar.abfallwirtschaft_stuttgart.attributes.start_time))|timestamp_custom('%d.%m.%Y') }} {{states.calendar.abfallwirtschaft_stuttgart.attributes.message|replace ('01-wöchentl.','')|replace ('02-wöchentl.','')|replace ('03-wöchentl.','')}}
      - service: persistent_notification.create
        data_template:
          title: "Erinnerung Müllabfuhr Morgen"
          message: >
              {{(as_timestamp(states.calendar.abfallwirtschaft_stuttgart.attributes.start_time))|timestamp_custom('%d.%m.%Y') }} {{states.calendar.abfallwirtschaft_stuttgart.attributes.message|replace ('01-wöchentl.','')|replace ('02-wöchentl.','')|replace ('03-wöchentl.','')}}
          notification_id: "waste_alert_12h"
