##############################################################
### Packages / Weather                                     ###
### @cvoid - https://github.com/bl0rp/Home-AssistantConfig ###
##############################################################

homeassistant:

#################
### Customize ###
#################

  customize:

    camera.regenradarstuttgart:
      friendly_name: Regen Radar Stuttgart
      icon: mdi:radar

    sensor.sunstate:
      friendly_name: Die Sonne ist
      icon: mdi:white-balance-sunny

    sensor.sun_next_setting:
      friendly_name: Nächster Sonnenuntergang
      icon: mdi:weather-sunset-down

    sensor.sun_next_rising:
      friendly_name: Nächster Sonnenaufgang
      icon: mdi:weather-sunset-up

    script.sun_info_pushbullet:
      friendly_name: Pushbullet Sonneninfo
      icon: mdi:white-balance-sunny

#####################################
### yr.no/darksky/wetter->German  ###
#####################################

    sun.sun:
      friendly_name: Sonne

###yr.no
    sensor.yr_fog:
      friendly_name: Nebel (yr.no)
    sensor.yr_cloudiness:
      friendly_name: Bewölkung  (yr.no)
      icon: mdi:cloud
    sensor.yr_dewpoint_temperature:
      friendly_name: Taupunkt  (yr.no)
    sensor.yr_humidity:
      friendly_name: Luftfeuchtigkeit  (yr.no)
      icon: mdi:water-percent
    sensor.yr_precipitation:
      friendly_name: Niederschlag  (yr.no)
      icon: mdi:weather-snowy-rainy
    sensor.yr_pressure:
      friendly_name: Luftdruck  (yr.no)
      icon: mdi:gauge
    sensor.yr_temperature:
      friendly_name: Außentemperatur  (yr.no)
      icon: mdi:thermometer
    sensor.yr_wind_speed:
      friendly_name: Windgeschwindigkeit  (yr.no)
      icon: mdi:weather-windy

###DarkSky
    sensor.dark_sky_apparent_temperature:
       friendly_name: Gefühlte Temperatur (DarkSky)
    sensor.dark_sky_cloud_coverage:
       friendly_name: Bewölkung (DarkSky)
    sensor.dark_sky_daily_high_apparent_temperature:
       friendly_name: Tageshöchsttemperatur (gefühlt) (DarkSky)
    sensor.dark_sky_daily_high_temperature:
       friendly_name: Tageshöchsttemperatur (DarkSky)
    sensor.dark_sky_daily_low_apparent_temperature:
       friendly_name: Tagesniedrigsttemperatur (gefühlt) (DarkSky)
    sensor.dark_sky_daily_low_temperature:
       friendly_name: Tagesniedrigsttemperatur (DarkSky)
    sensor.dark_sky_daily_max_precip_intensity:
       friendly_name: Tageshöchstniederschlag (DarkSky)
    sensor.dark_sky_daily_summary:
       friendly_name: Tageszusammenfassung (DarkSky)
    sensor.dark_sky_dew_point:
       friendly_name: Taupunkt (DarkSky)
    sensor.dark_sky_hourly_summary:
       friendly_name: Stündliche Zusammenfassung (DarkSky)
    sensor.dark_sky_humidity:
       friendly_name: Luftfeuchtigkeit (DarkSky)
    sensor.dark_sky_minutely_summary:
       friendly_name: Minütliche Zusammenfassung (DarkSky)
    sensor.dark_sky_ozone:
       friendly_name: Ozon (DarkSky)
    sensor.dark_sky_precip:
       friendly_name: Niederschlag (DarkSky)
    sensor.dark_sky_precip_intensity:
       friendly_name: Niederschlag Intensität (DarkSky)
    sensor.dark_sky_precip_probability:
       friendly_name: Niederschlagswahrscheinlichkeit (DarkSky)
    sensor.dark_sky_pressure:
       friendly_name: Luftdruck (DarkSky)
    sensor.dark_sky_summary:
       friendly_name: Zusammenfassung (DarkSky)
    sensor.dark_sky_temperature:
       friendly_name: Außentemperatur (DarkSky)
    sensor.dark_sky_visibility:
       friendly_name: Sichtweite (DarkSky)
    sensor.dark_sky_wind_bearing:
       friendly_name: Windrichtung (DarkSky)
    sensor.dark_sky_wind_speed:
       friendly_name: Windgeschwindigkeit (DarkSky)

#################
### Radar Map ###
#################

camera:
  - platform: generic
    name: RegenRadarStuttgart
    still_image_url: https://www.niederschlagsradar.de/image.ashx?type=regioloop&regio=stg&j=&m=&d=&mi=&uhr=&bliksem=0&voor=&srt=loop1stunde


group:
  wetter_all:
    name: Wetter
    icon: mdi:weather-partlycloudy
    entities:
      - sensor.sunstate
      - sensor.moon
      - sensor.sun_next_setting
      - sensor.sun_next_rising
      - camera.regenradarstuttgart
      - sensor.yr_temperature
      - sensor.dark_sky_temperature
      - sensor.yr_humidity
      - sensor.dark_sky_humidity
      - sensor.yr_cloudiness
      - sensor.dark_sky_cloud_coverage
      - sensor.yr_precipitation
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - script.sun_info_pushbullet

  wetter_yr:
    name: Wetter via yr.no
    icon: mdi:weather-partlycloudy
    entities:
      - sensor.yr_temperature
      - sensor.yr_symbol
      - sensor.yr_cloudiness
      - sensor.yr_dewpoint_temperature
      - sensor.yr_humidity
      - sensor.yr_precipitation
      - sensor.yr_pressure
      - sensor.yr_wind_speed
      - sensor.yr_fog

  wetter_darksky:
    name: Wetter via DarkSky
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed


###############
### Sensors ###
###############

sensor:

###############
### Sources ###
###############

#yr.no
  - platform: yr
    monitored_conditions:
        - temperature
        - symbol
        - precipitation
        - windSpeed
        - pressure
        - humidity
        - fog
        - cloudiness
        - dewpointTemperature
#Darksky
  - platform: darksky
    api_key: !secret darksky_api_key
    update_interval: '00:03'
    language: de
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
#Moon
  - platform: moon

#DWD Weather Warn
  - platform: dwd_weather_warnings
    region_name: Stuttgart

################
### Template ###
################

  - platform: template
    sensors:
      sunstate:
        value_template: >
          {{ 'am Himmel' if is_state('sun.sun', 'above_horizon') else 'unter dem Horizont' }}
        icon_template: >
          {% if is_state('sun.sun', 'above_horizon') %}mdi:weather-sunny{% else %}mdi:waether-night{% endif %}

  - platform: template
    sensors:
      sun_next_setting:
        value_template: '{% if states.sun.sun %}{{ ((as_timestamp(states.sun.sun.attributes.next_setting)) | timestamp_local) [11:19] }}{% endif %}'

  - platform: template
    sensors:
      sun_next_rising:
        value_template: '{% if states.sun.sun %}{{ ((as_timestamp(states.sun.sun.attributes.next_rising)) | timestamp_local) [11:19] }}{% endif %}'



###############
### Scripts ###
###############

script:
  sun_info_pushbullet:
    alias: "Sun Information via PB"
    sequence:
      service: notify.pushbullet
      data:
        title: "({{ now().strftime('%d.%m.%Y %H:%M:%S') }}): Die Sonne ist {{ states.sensor.sunstate.state }}."
        message: >
           Nächster Sonnenuntergang: {{ states.sensor.sun_next_setting.state }}
           Nächster Sonnenaufgang: {{ states.sensor.sun_next_rising.state }}
