homeassistant:

  customize:
    sensor.zwave_fibaro_mpd_1_electric_consumed_kwh:
      friendly_name: Boxen
      icon: mdi:chart-line



sensor:
### MPD Dose
  - platform: template
    sensors:
      zwave_fibaro_mpd_1_use:
        friendly_name: Gerät in Benutzung?
        value_template: "{% if states('sensor.zwave_fibaro_mpd_1_power') | int > 0.2 %}Ja{% else %}Nein{% endif %}"
        icon_template: "{% if states('sensor.zwave_fibaro_mpd_1_power') | int > 0.2 %}mdi:flash{% else %}mdi:flash-off{% endif %}"

      zwave_fibaro_mpd_1_kosten_gesamt:
        friendly_name: Gesamtkosten
        unit_of_measurement: "€"
        value_template: >-
          {{ states('sensor.zwave_fibaro_mpd_1_electric_consumed_kwh')   | multiply(0.2657) | round(2) }}




### Motion last triggered
  - platform: template
    sensors:
      multisensor_motion_last_triggered:
        friendly_name: "Multisensor Motion Last Triggered"
        value_template: >-
          {{ as_timestamp(states.binary_sensor.zwave_multisensor_6_elw_home_security_motion_detection.last_changed)|timestamp_custom('%d.%m.%Y %H:%M:%S') }}
